/* --- data_packet_groups.obj batch drafts (2026-07-26) --- */

/* data_packet_group_append_packet_header (0x11abb0) — readable C lift. */
char data_packet_group_append_packet_header(void *group, unsigned char *buf_base,
                                           short *offset_ptr, short type_index)
{
  unsigned char *pos;
  unsigned int limit;

  pos = buf_base + *offset_ptr;
  if (buf_base == 0) {
    display_assert((const char *)0x28f318, (const char *)0x28f1f0, 0xac, 1);
    system_exit(-1);
  }
  if (*offset_ptr < 0) {
    display_assert((const char *)0x28f3c4, (const char *)0x28f1f0, 0xad, 1);
    system_exit(-1);
  }
  if (type_index < 0 || type_index >= *(short *)((char *)group + 4)) {
    display_assert((const char *)0x28f380, (const char *)0x28f1f0, 0xae, 1);
    system_exit(-1);
  }
  limit = *(unsigned int *)((char *)group + 0xc);
  if ((unsigned int)((int)*offset_ptr + 1) >= limit) {
    *(unsigned int *)0x46e804 = 0x28f350u;
    return 0;
  }
  *pos = (unsigned char)type_index;
  FUN_00118be0((void *)0x3220c0, pos, 1);
  (*offset_ptr)++;
  *(unsigned int *)0x46e804 = 0;
  return 1;
}

/* encode_packet_group (0x11aca0) — readable C lift. */
bool encode_packet_group(group_definition *group, void *data, char *encoded_buf,
                         int32_t *encoded_size, int16_t type, int version)
{
  unsigned int err;
  char *entry;
  int definition;

  err = 0;
  if (!group) {
    display_assert((const char *)0x28f408, (const char *)0x28f1f0, 0x84, 1);
    system_exit(-1);
  }
  if (type < 0 || type >= *(int16_t *)((char *)group + 4)) {
    display_assert((const char *)0x28f380, (const char *)0x28f1f0, 0x85, 1);
    system_exit(-1);
  }
  if (!encoded_buf || !encoded_size) {
    display_assert((const char *)0x28f318, (const char *)0x28f1f0, 0x86, 1);
    system_exit(-1);
  }
  entry = *(char **)((char *)group + 0x10) + (int)type * 8;
  definition = *(int *)(entry + 4);
  if (!definition) {
    display_assert((const char *)0x28f3f4, (const char *)0x28f1f0, 0x8b, 1);
    system_exit(-1);
  }
  if (!FUN_0011b650(definition, (short)version, data, encoded_buf,
                    (short *)encoded_size, *(short *)((char *)group + 0xc))) {
    err = 0x28f3dcu;
  } else if (!data_packet_group_append_packet_header(group,
                                                    (unsigned char *)encoded_buf,
                                                    (short *)encoded_size,
                                                    type)) {
    err = *(unsigned int *)0x46e804;
  }
  *(unsigned int *)0x46e804 = err;
  return err == 0;
}


/* compute_packet_field_sizes (0x11add0) — XBE naked draft (batch 118). */
#if defined(__clang__)
static char * (*const b11add0_c8d9d0)(char *buffer, const char *format, ...) = csprintf;
static void (*const b11add0_assert)(const char *, const char *, int, bool) = display_assert;
static void (*const b11add0_exitfn)(int) = system_exit;
static void (*const b11add0_c11add0)(packet_definition *def, short *param_2, short *param_3, short *param_4) = compute_packet_field_sizes;

__attribute__((naked, noinline))
void compute_packet_field_sizes(packet_definition *def __attribute__((unused)), short *param_2 __attribute__((unused)), short *param_3 __attribute__((unused)), short *param_4 __attribute__((unused)))
{
  __asm__ volatile(
      "pushl %%ebp\n\t"
      "movl %%esp, %%ebp\n\t"
      "subl $0xc, %%esp\n\t"
      "movl 0x10(%%ebp), %%eax\n\t"
      "cmpw $9, (%%eax)\n\t"
      "pushl %%esi\n\t"
      "movl %%eax, %%esi\n\t"
      "movl $0, -0xc(%%ebp)\n\t"
      "je .Lcompute_packet_field_sizes_16\n\t"
      "pushl %%ebx\n\t"
      "movl 0x8(%%ebp), %%ebx\n\t"
      "pushl %%edi\n\t"
      "movl 0x10(%%ebp), %%edi\n\t"
      ".Lcompute_packet_field_sizes_1:\n\t"
      "movw (%%esi), %%ax\n\t"
      "testw %%ax, %%ax\n\t"
      "jl .Lcompute_packet_field_sizes_2\n\t"
      "cmpw $0xa, %%ax\n\t"
      "jl .Lcompute_packet_field_sizes_3\n\t"
      ".Lcompute_packet_field_sizes_2:\n\t"
      "movl (%%ebx), %%eax\n\t"
      "pushl $1\n\t"
      "pushl $0x8e\n\t"
      "pushl $0x28f498\n\t"
      "pushl %%eax\n\t"
      "pushl $0x28f450\n\t"
      "pushl $0x5ab100\n\t"
      "call *%[c8d9d0]\n\t"
      "addl $0xc, %%esp\n\t"
      "pushl %%eax\n\t"
      "call *%[assert]\n\t"
      "pushl $-1\n\t"
      "call *%[exitfn]\n\t"
      "addl $0x14, %%esp\n\t"
      ".Lcompute_packet_field_sizes_3:\n\t"
      "cmpw $0, 0x2(%%esi)\n\t"
      "jg .Lcompute_packet_field_sizes_4\n\t"
      "movl (%%ebx), %%ecx\n\t"
      "pushl $1\n\t"
      "pushl $0x90\n\t"
      "pushl $0x28f498\n\t"
      "pushl %%ecx\n\t"
      "pushl $0x28f41c\n\t"
      "pushl $0x5ab100\n\t"
      "call *%[c8d9d0]\n\t"
      "addl $0xc, %%esp\n\t"
      "pushl %%eax\n\t"
      "call *%[assert]\n\t"
      "pushl $-1\n\t"
      "call *%[exitfn]\n\t"
      "addl $0x14, %%esp\n\t"
      ".Lcompute_packet_field_sizes_4:\n\t"
      "movw 0xa(%%ebx), %%ax\n\t"
      "cmpw 0x4(%%esi), %%ax\n\t"
      "jl .Lcompute_packet_field_sizes_15\n\t"
      "movw 0x6(%%esi), %%cx\n\t"
      "cmpw %%cx, %%ax\n\t"
      "jle .Lcompute_packet_field_sizes_5\n\t"
      "testw %%cx, %%cx\n\t"
      "jne .Lcompute_packet_field_sizes_15\n\t"
      ".Lcompute_packet_field_sizes_5:\n\t"
      "movswl (%%esi), %%eax\n\t"
      "cmpl $9, %%eax\n\t"
      "ja .Lcompute_packet_field_sizes_14\n\t"
      "jmp *.Lcompute_packet_field_sizes_jt(,%%eax,4)\n\t"
      ".Lcompute_packet_field_sizes_6:\n\t"
      "movw 0x2(%%esi), %%di\n\t"
      "jmp .Lcompute_packet_field_sizes_15\n\t"
      ".Lcompute_packet_field_sizes_7:\n\t"
      "movw 0x2(%%esi), %%di\n\t"
      "shlw $1, %%di\n\t"
      "jmp .Lcompute_packet_field_sizes_15\n\t"
      ".Lcompute_packet_field_sizes_8:\n\t"
      "movw 0x2(%%esi), %%di\n\t"
      "shlw $2, %%di\n\t"
      "jmp .Lcompute_packet_field_sizes_15\n\t"
      ".Lcompute_packet_field_sizes_9:\n\t"
      "movw 0x2(%%esi), %%di\n\t"
      "shlw $3, %%di\n\t"
      "jmp .Lcompute_packet_field_sizes_15\n\t"
      ".Lcompute_packet_field_sizes_10:\n\t"
      "movw 0x2(%%esi), %%di\n\t"
      "incw %%di\n\t"
      "jmp .Lcompute_packet_field_sizes_15\n\t"
      ".Lcompute_packet_field_sizes_11:\n\t"
      "movw 0x2(%%esi), %%di\n\t"
      "addw $2, %%di\n\t"
      "jmp .Lcompute_packet_field_sizes_15\n\t"
      ".Lcompute_packet_field_sizes_12:\n\t"
      "leal -0x8(%%ebp), %%edx\n\t"
      "pushl %%edx\n\t"
      "leal 0xa(%%esi), %%eax\n\t"
      "pushl %%eax\n\t"
      "leal -0x4(%%ebp), %%ecx\n\t"
      "pushl %%ecx\n\t"
      "pushl %%ebx\n\t"
      "call *%[c11add0]\n\t"
      "movswl -0x8(%%ebp), %%eax\n\t"
      "xorl %%edi, %%edi\n\t"
      "movw 0x2(%%esi), %%di\n\t"
      "imulw -0x4(%%ebp), %%di\n\t"
      "leal (%%eax,%%eax,4), %%edx\n\t"
      "addl $0x10, %%esp\n\t"
      "leal (%%esi,%%edx,2), %%esi\n\t"
      "addl $2, %%edi\n\t"
      "jmp .Lcompute_packet_field_sizes_15\n\t"
      ".Lcompute_packet_field_sizes_13:\n\t"
      "xorl %%edi, %%edi\n\t"
      "jmp .Lcompute_packet_field_sizes_15\n\t"
      ".Lcompute_packet_field_sizes_14:\n\t"
      "pushl $1\n\t"
      "pushl $0xc1\n\t"
      "pushl $0x28f498\n\t"
      "pushl $0\n\t"
      "call *%[assert]\n\t"
      "pushl $-1\n\t"
      "call *%[exitfn]\n\t"
      "addl $0x14, %%esp\n\t"
      ".Lcompute_packet_field_sizes_15:\n\t"
      "movl -0xc(%%ebp), %%edx\n\t"
      "movw %%di, 0x8(%%esi)\n\t"
      "addl %%edi, %%edx\n\t"
      "addl $0xa, %%esi\n\t"
      "cmpw $9, (%%esi)\n\t"
      "movl %%edx, -0xc(%%ebp)\n\t"
      "jne .Lcompute_packet_field_sizes_1\n\t"
      "movl 0x10(%%ebp), %%eax\n\t"
      "popl %%edi\n\t"
      "popl %%ebx\n\t"
      ".Lcompute_packet_field_sizes_16:\n\t"
      "movl 0x14(%%ebp), %%ecx\n\t"
      "testl %%ecx, %%ecx\n\t"
      "je .Lcompute_packet_field_sizes_17\n\t"
      "subl %%eax, %%esi\n\t"
      "movl $0x66666667, %%eax\n\t"
      "imull %%esi\n\t"
      "sarl $2, %%edx\n\t"
      "movl %%edx, %%eax\n\t"
      "shrl $0x1f, %%eax\n\t"
      "leal 0x1(%%edx,%%eax,1), %%edx\n\t"
      "movw %%dx, (%%ecx)\n\t"
      ".Lcompute_packet_field_sizes_17:\n\t"
      "movl 0xc(%%ebp), %%eax\n\t"
      "testl %%eax, %%eax\n\t"
      "popl %%esi\n\t"
      "je .Lcompute_packet_field_sizes_18\n\t"
      "movw -0xc(%%ebp), %%cx\n\t"
      "movw %%cx, (%%eax)\n\t"
      ".Lcompute_packet_field_sizes_18:\n\t"
      "movl %%ebp, %%esp\n\t"
      "popl %%ebp\n\t"
      "ret\n\t"
      ".section .rdata,\"dr\"\n\t"
      ".Lcompute_packet_field_sizes_jt:\n\t"
      ".long .Lcompute_packet_field_sizes_6\n\t"
      ".long .Lcompute_packet_field_sizes_6\n\t"
      ".long .Lcompute_packet_field_sizes_7\n\t"
      ".long .Lcompute_packet_field_sizes_8\n\t"
      ".long .Lcompute_packet_field_sizes_9\n\t"
      ".long .Lcompute_packet_field_sizes_10\n\t"
      ".long .Lcompute_packet_field_sizes_11\n\t"
      ".long .Lcompute_packet_field_sizes_12\n\t"
      ".long .Lcompute_packet_field_sizes_6\n\t"
      ".long .Lcompute_packet_field_sizes_13\n\t"
      ".text\n\t"
      :
      : [c8d9d0] "m"(b11add0_c8d9d0), [assert] "m"(b11add0_assert), [exitfn] "m"(b11add0_exitfn), [c11add0] "m"(b11add0_c11add0)
      : "memory");
}
#else
#error "compute_packet_field_sizes: clang naked draft required"
#endif


/* _data_packet_encode (0x11afa0) — XBE naked draft (batch 109). */
#if defined(__clang__)
static int (*const b11afa0_c119cc0)(int *param_1, int param_2, short param_3, int param_4) = FUN_00119cc0;
static bool (*const b11afa0_c11a230)(int *state, const char *source, short max_length) = FUN_0011a230;
static void (*const b11afa0_assert)(const char *, const char *, int, bool) = display_assert;
static void (*const b11afa0_exitfn)(int) = system_exit;
static bool (*const b11afa0_c119df0)(int *param_1, int param_2, int param_3) = FUN_00119df0;
static void (*const b11afa0_c11add0)(packet_definition *def, short *param_2, short *param_3, short *param_4) = compute_packet_field_sizes;
static void (*const b11afa0_c11afa0)(int param_1, int *param_2, short param_3, void *param_4, short param_5, int param_6, short *param_7) = _data_packet_encode;

__attribute__((naked, noinline))
void _data_packet_encode(int param_1 __attribute__((unused)), int *param_2 __attribute__((unused)), short param_3 __attribute__((unused)), void *param_4 __attribute__((unused)), short param_5 __attribute__((unused)), int param_6 __attribute__((unused)), short *param_7 __attribute__((unused)))
{
  __asm__ volatile(
      "pushl %%ebp\n\t"
      "movl %%esp, %%ebp\n\t"
      "subl $0x18, %%esp\n\t"
      "movl 0x1c(%%ebp), %%eax\n\t"
      "cmpw $9, (%%eax)\n\t"
      "pushl %%esi\n\t"
      "pushl %%edi\n\t"
      "movl 0x14(%%ebp), %%edi\n\t"
      "movl %%eax, %%esi\n\t"
      "movl %%edi, -0x10(%%ebp)\n\t"
      "je .L_data_packet_encode_30\n\t"
      "pushl %%ebx\n\t"
      "movl 0xc(%%ebp), %%ebx\n\t"
      ".L_data_packet_encode_1:\n\t"
      "movl 0x10(%%ebp), %%ecx\n\t"
      "cmpw 0x4(%%esi), %%cx\n\t"
      "jl .L_data_packet_encode_23\n\t"
      "movw 0x6(%%esi), %%ax\n\t"
      "cmpw %%ax, %%cx\n\t"
      "jle .L_data_packet_encode_2\n\t"
      "testw %%ax, %%ax\n\t"
      "jne .L_data_packet_encode_23\n\t"
      ".L_data_packet_encode_2:\n\t"
      "movswl (%%esi), %%eax\n\t"
      "cmpl $8, %%eax\n\t"
      "ja .L_data_packet_encode_22\n\t"
      "jmp *.L_data_packet_encode_jt0(,%%eax,4)\n\t"
      ".L_data_packet_encode_3:\n\t"
      "pushl $1\n\t"
      ".L_data_packet_encode_4:\n\t"
      "xorl %%eax, %%eax\n\t"
      "movw 0x2(%%esi), %%ax\n\t"
      "pushl %%eax\n\t"
      "pushl %%edi\n\t"
      "pushl %%ebx\n\t"
      "call *%[c119cc0]\n\t"
      "addl $0x10, %%esp\n\t"
      "jmp .L_data_packet_encode_29\n\t"
      ".L_data_packet_encode_5:\n\t"
      "xorl %%ecx, %%ecx\n\t"
      "movw 0x2(%%esi), %%cx\n\t"
      "pushl $-2\n\t"
      "pushl %%ecx\n\t"
      "pushl %%edi\n\t"
      "pushl %%ebx\n\t"
      "call *%[c119cc0]\n\t"
      "addl $0x10, %%esp\n\t"
      "jmp .L_data_packet_encode_29\n\t"
      ".L_data_packet_encode_6:\n\t"
      "xorl %%edx, %%edx\n\t"
      "movw 0x2(%%esi), %%dx\n\t"
      "pushl $-4\n\t"
      "pushl %%edx\n\t"
      "pushl %%edi\n\t"
      "pushl %%ebx\n\t"
      "call *%[c119cc0]\n\t"
      "addl $0x10, %%esp\n\t"
      "jmp .L_data_packet_encode_29\n\t"
      ".L_data_packet_encode_7:\n\t"
      "pushl $-8\n\t"
      "jmp .L_data_packet_encode_4\n\t"
      ".L_data_packet_encode_8:\n\t"
      "xorl %%ecx, %%ecx\n\t"
      "movw 0x2(%%esi), %%cx\n\t"
      "pushl %%ecx\n\t"
      "pushl %%edi\n\t"
      "pushl %%ebx\n\t"
      "call *%[c11a230]\n\t"
      "addl $0xc, %%esp\n\t"
      "jmp .L_data_packet_encode_29\n\t"
      ".L_data_packet_encode_9:\n\t"
      "movw (%%edi), %%di\n\t"
      "testw %%di, %%di\n\t"
      "jl .L_data_packet_encode_10\n\t"
      "cmpw 0x2(%%esi), %%di\n\t"
      "jle .L_data_packet_encode_11\n\t"
      ".L_data_packet_encode_10:\n\t"
      "pushl $1\n\t"
      "pushl $0xfd\n\t"
      "pushl $0x28f498\n\t"
      "pushl $0x28f4f0\n\t"
      "call *%[assert]\n\t"
      "pushl $-1\n\t"
      "call *%[exitfn]\n\t"
      "addl $0x14, %%esp\n\t"
      ".L_data_packet_encode_11:\n\t"
      "testw %%di, %%di\n\t"
      "jl .L_data_packet_encode_12\n\t"
      "cmpw 0x2(%%esi), %%di\n\t"
      "jle .L_data_packet_encode_13\n\t"
      ".L_data_packet_encode_12:\n\t"
      "xorl %%edi, %%edi\n\t"
      ".L_data_packet_encode_13:\n\t"
      "movswl 0x2(%%esi), %%edx\n\t"
      "movswl %%di, %%eax\n\t"
      "pushl %%edx\n\t"
      "pushl %%eax\n\t"
      "pushl %%ebx\n\t"
      "call *%[c119df0]\n\t"
      "movl -0x10(%%ebp), %%eax\n\t"
      "pushl $1\n\t"
      "pushl %%edi\n\t"
      "addl $2, %%eax\n\t"
      "pushl %%eax\n\t"
      "pushl %%ebx\n\t"
      "call *%[c119cc0]\n\t"
      "movl -0x10(%%ebp), %%edi\n\t"
      "addl $0x1c, %%esp\n\t"
      "jmp .L_data_packet_encode_29\n\t"
      ".L_data_packet_encode_14:\n\t"
      "xorl %%ecx, %%ecx\n\t"
      "movw 0x2(%%esi), %%cx\n\t"
      "pushl $1\n\t"
      "pushl %%ecx\n\t"
      "pushl %%edi\n\t"
      "pushl %%ebx\n\t"
      "call *%[c119cc0]\n\t"
      "addl $0x10, %%esp\n\t"
      "jmp .L_data_packet_encode_29\n\t"
      ".L_data_packet_encode_15:\n\t"
      "movl -0x10(%%ebp), %%edx\n\t"
      "movw (%%edi), %%di\n\t"
      "leal -0xc(%%ebp), %%ecx\n\t"
      "pushl %%ecx\n\t"
      "addl $2, %%edx\n\t"
      "leal 0xa(%%esi), %%eax\n\t"
      "pushl %%eax\n\t"
      "movl %%edx, -0x14(%%ebp)\n\t"
      "movl 0x8(%%ebp), %%edx\n\t"
      "pushl $0\n\t"
      "pushl %%edx\n\t"
      "call *%[c11add0]\n\t"
      "addl $0x10, %%esp\n\t"
      "testw %%di, %%di\n\t"
      "jl .L_data_packet_encode_16\n\t"
      "cmpw 0x2(%%esi), %%di\n\t"
      "jle .L_data_packet_encode_17\n\t"
      ".L_data_packet_encode_16:\n\t"
      "pushl $1\n\t"
      "pushl $0x119\n\t"
      "pushl $0x28f498\n\t"
      "pushl $0x28f4c0\n\t"
      "call *%[assert]\n\t"
      "pushl $-1\n\t"
      "call *%[exitfn]\n\t"
      "addl $0x14, %%esp\n\t"
      ".L_data_packet_encode_17:\n\t"
      "testw %%di, %%di\n\t"
      "jl .L_data_packet_encode_18\n\t"
      "cmpw 0x2(%%esi), %%di\n\t"
      "jle .L_data_packet_encode_19\n\t"
      ".L_data_packet_encode_18:\n\t"
      "xorl %%edi, %%edi\n\t"
      ".L_data_packet_encode_19:\n\t"
      "movswl 0x2(%%esi), %%eax\n\t"
      "movswl %%di, %%ecx\n\t"
      "pushl %%eax\n\t"
      "pushl %%ecx\n\t"
      "pushl %%ebx\n\t"
      "call *%[c119df0]\n\t"
      "addl $0xc, %%esp\n\t"
      "testw %%di, %%di\n\t"
      "jle .L_data_packet_encode_21\n\t"
      "movzwl %%di, %%edx\n\t"
      "movl %%edx, -0x18(%%ebp)\n\t"
      "leal (%%esp), %%esp\n\t"
      ".L_data_packet_encode_20:\n\t"
      "movl -0x14(%%ebp), %%edi\n\t"
      "movl 0x10(%%ebp), %%ecx\n\t"
      "movl 0x8(%%ebp), %%edx\n\t"
      "pushl $0\n\t"
      "leal 0xa(%%esi), %%eax\n\t"
      "pushl %%eax\n\t"
      "leal -0x8(%%ebp), %%eax\n\t"
      "pushl %%eax\n\t"
      "pushl %%edi\n\t"
      "pushl %%ecx\n\t"
      "pushl %%ebx\n\t"
      "pushl %%edx\n\t"
      "call *%[c11afa0]\n\t"
      "movswl -0x8(%%ebp), %%eax\n\t"
      "addl %%eax, %%edi\n\t"
      "movl -0x18(%%ebp), %%eax\n\t"
      "addl $0x1c, %%esp\n\t"
      "decl %%eax\n\t"
      "movl %%edi, -0x14(%%ebp)\n\t"
      "movl %%eax, -0x18(%%ebp)\n\t"
      "jne .L_data_packet_encode_20\n\t"
      ".L_data_packet_encode_21:\n\t"
      "movswl -0xc(%%ebp), %%eax\n\t"
      "movl -0x10(%%ebp), %%edi\n\t"
      "leal (%%eax,%%eax,4), %%ecx\n\t"
      "leal (%%esi,%%ecx,2), %%esi\n\t"
      "jmp .L_data_packet_encode_29\n\t"
      ".L_data_packet_encode_22:\n\t"
      "pushl $1\n\t"
      "pushl $0x129\n\t"
      "jmp .L_data_packet_encode_28\n\t"
      ".L_data_packet_encode_23:\n\t"
      "movswl (%%esi), %%eax\n\t"
      "cmpl $8, %%eax\n\t"
      "ja .L_data_packet_encode_27\n\t"
      "jmp *.L_data_packet_encode_jt1(,%%eax,4)\n\t"
      ".L_data_packet_encode_24:\n\t"
      "xorl %%edx, %%edx\n\t"
      "movw 0x2(%%esi), %%dx\n\t"
      "pushl $1\n\t"
      "pushl %%edx\n\t"
      "pushl $0\n\t"
      "pushl %%ebx\n\t"
      "call *%[c119cc0]\n\t"
      "addl $0x10, %%esp\n\t"
      "jmp .L_data_packet_encode_29\n\t"
      ".L_data_packet_encode_25:\n\t"
      "pushl $1\n\t"
      "pushl $1\n\t"
      "leal -0x1(%%ebp), %%eax\n\t"
      "pushl %%eax\n\t"
      "pushl %%ebx\n\t"
      "movb $0, -0x1(%%ebp)\n\t"
      "call *%[c119cc0]\n\t"
      "addl $0x10, %%esp\n\t"
      "jmp .L_data_packet_encode_29\n\t"
      ".L_data_packet_encode_26:\n\t"
      "movswl 0x2(%%esi), %%ecx\n\t"
      "pushl %%ecx\n\t"
      "pushl $0\n\t"
      "pushl %%ebx\n\t"
      "call *%[c119df0]\n\t"
      "addl $0xc, %%esp\n\t"
      "jmp .L_data_packet_encode_29\n\t"
      ".L_data_packet_encode_27:\n\t"
      "pushl $1\n\t"
      "pushl $0x144\n\t"
      ".L_data_packet_encode_28:\n\t"
      "pushl $0x28f498\n\t"
      "pushl $0\n\t"
      "call *%[assert]\n\t"
      "pushl $-1\n\t"
      "call *%[exitfn]\n\t"
      "addl $0x14, %%esp\n\t"
      ".L_data_packet_encode_29:\n\t"
      "movswl 0x8(%%esi), %%edx\n\t"
      "addl %%edx, %%edi\n\t"
      "addl $0xa, %%esi\n\t"
      "cmpw $9, (%%esi)\n\t"
      "movl %%edi, -0x10(%%ebp)\n\t"
      "jne .L_data_packet_encode_1\n\t"
      "movl 0x1c(%%ebp), %%eax\n\t"
      "popl %%ebx\n\t"
      ".L_data_packet_encode_30:\n\t"
      "movl 0x20(%%ebp), %%ecx\n\t"
      "testl %%ecx, %%ecx\n\t"
      "je .L_data_packet_encode_31\n\t"
      "subl %%eax, %%esi\n\t"
      "movl $0x66666667, %%eax\n\t"
      "imull %%esi\n\t"
      "sarl $2, %%edx\n\t"
      "movl %%edx, %%eax\n\t"
      "shrl $0x1f, %%eax\n\t"
      "leal 0x1(%%edx,%%eax,1), %%edx\n\t"
      "movw %%dx, (%%ecx)\n\t"
      ".L_data_packet_encode_31:\n\t"
      "movl 0x18(%%ebp), %%eax\n\t"
      "testl %%eax, %%eax\n\t"
      "je .L_data_packet_encode_32\n\t"
      "subl 0x14(%%ebp), %%edi\n\t"
      "movw %%di, (%%eax)\n\t"
      ".L_data_packet_encode_32:\n\t"
      "popl %%edi\n\t"
      "popl %%esi\n\t"
      "movl %%ebp, %%esp\n\t"
      "popl %%ebp\n\t"
      "ret\n\t"
      ".section .rdata,\"dr\"\n\t"
      ".L_data_packet_encode_jt0:\n\t"
      ".long .L_data_packet_encode_29\n\t"
      ".long .L_data_packet_encode_3\n\t"
      ".long .L_data_packet_encode_5\n\t"
      ".long .L_data_packet_encode_6\n\t"
      ".long .L_data_packet_encode_7\n\t"
      ".long .L_data_packet_encode_8\n\t"
      ".long .L_data_packet_encode_9\n\t"
      ".long .L_data_packet_encode_15\n\t"
      ".long .L_data_packet_encode_14\n\t"
      ".text\n\t"
      ".section .rdata,\"dr\"\n\t"
      ".L_data_packet_encode_jt1:\n\t"
      ".long .L_data_packet_encode_29\n\t"
      ".long .L_data_packet_encode_24\n\t"
      ".long .L_data_packet_encode_24\n\t"
      ".long .L_data_packet_encode_24\n\t"
      ".long .L_data_packet_encode_24\n\t"
      ".long .L_data_packet_encode_25\n\t"
      ".long .L_data_packet_encode_26\n\t"
      ".long .L_data_packet_encode_26\n\t"
      ".long .L_data_packet_encode_24\n\t"
      ".text\n\t"
      :
      : [c119cc0] "m"(b11afa0_c119cc0), [c11a230] "m"(b11afa0_c11a230), [assert] "m"(b11afa0_assert), [exitfn] "m"(b11afa0_exitfn), [c119df0] "m"(b11afa0_c119df0), [c11add0] "m"(b11afa0_c11add0), [c11afa0] "m"(b11afa0_c11afa0)
      : "memory");
}
#else
#error "_data_packet_encode: clang naked draft required"
#endif

