#include <stdint.h>
/*
 * telnet_console.c — Debug telnet server for runtime console access.
 *
 * Listens on TCP port 23 (telnet). Accepts exactly one client connection at a
 * time. Each process tick checks for new connections and forwards received data
 * to the HS (HaloScript) command processor via FUN_00130b70.
 *
 * Globals layout at 0x46eee0 (0x8c bytes, zeroed by initialize/dispose):
 *   [+0x00] int*  listening_endpoint  — TCP listening socket wrapper
 *   [+0x04] int*  clients[0].ep       — accepted client endpoint (one slot)
 *   [+0x08] char  clients[0].buf[128] — telnet line input buffer
 *   [+0x88] char  initialized         — non-zero when subsystem is live
 */

/*
 * Transport endpoint helpers — not in kb.json (only used here).
 * All calls go through hardcoded function-pointer casts.
 *
 *   0x82d70  create_transport_endpoint(int type) -> int* (NULL on failure)
 *   0x83ce0  bind_endpoint(int *ep, void *addr)  -> int16_t (0=ok)
 *   0x843a0  listen_endpoint(int *ep)             -> int16_t (0=ok)
 *   0x848c0  destroy_endpoint(int *ep)            -> void
 *   0x83040  endpoint_readable(int *ep, uint16_t timeout_ms) -> char (bool)
 *   0x84450  accept_endpoint(int *ep)             -> int* (NULL if none)
 *   0x82f50  send_endpoint(int *ep, char *buf, int len) -> int (<=0 = error)
 *   0x82e50  recv_endpoint(int *ep, char *buf, int maxlen) -> int (<=0 = error)
 *   0x81c80  transport_error_string(int16_t code) -> char* (description)
 *   0x130b70 process_telnet_client_input(char *buf, int len)
 *            -> char (bool: 1=ok, 0=close client); ESI = &clients[0] (implicit)
 */

/* telnet_console_globals layout (as addressed from 0x46eee0): */
#define tc_listening_ep (*(int **)0x46eee0)
#define tc_client0_ep (*(int **)0x46eee4)
#define tc_initialized (*(char *)0x46ef68)

/* Maximum number of simultaneous telnet clients. */
#define TELNET_CONSOLE_MAX_CLIENTS 1

/* TCP transport type code. */
#define TRANSPORT_TYPE_TCP 0x12

/*
 * telnet_console_initialize — create listening TCP socket on port 23.
 *
 * Allocates a TCP transport endpoint, binds it to INADDR_ANY:23, and sets
 * the socket to listen.  Sets the initialized flag on success; logs and
 * tears down on any failure.
 */
void telnet_console_initialize(void)
{
  int16_t result;
  int *ep;

  /* Transport address struct (0x18 bytes).  Layout inferred from bind_endpoint
   * internals: ip at [+0], unknown word at [+0x10], port (host order) at
   * [+0x12].  All other bytes are zero (INADDR_ANY, no options). */
  struct {
    uint32_t ip; /* [+0x00] INADDR_ANY = 0 */
    uint8_t pad[0x10]; /* [+0x04..+0x0f] zeroed */
    uint16_t unk_10; /* [+0x10] = 0x0004 (observed, unknown field) */
    uint16_t port; /* [+0x12] = 23 (telnet), host byte order */
    uint32_t pad2; /* [+0x14] = 0 */
  } addr;

  /* Zero the globals block before populating it. */
  csmemset((void *)0x46eee0, 0, 0x8c);

  /* Allocate a TCP endpoint. */
  ep = ((int *(*)(int))0x82d70)(TRANSPORT_TYPE_TCP);
  if (ep == 0) {
    error(2, "create_transport_endpoint() failed on telnet console endpoint");
    return;
  }
  tc_listening_ep = ep;

  /* Build the bind address: INADDR_ANY on port 23. */
  csmemset(&addr, 0, sizeof(addr));
  addr.unk_10 = 0x0004;
  addr.port = 0x0017; /* 23 decimal = telnet */

  result = ((int16_t(*)(int *, void *))0x83ce0)(ep, &addr);
  if (result != 0) {
    error(2, "bind_endpoint() failed on telnet console endpoint");
    goto fail;
  }

  result = ((int16_t(*)(int *))0x843a0)(ep);
  if (result != 0) {
    error(2, "listen_endpoint() failed on telnet console endpoint");
    goto fail;
  }

  /* Mark subsystem active. */
  tc_initialized = 1;
  return;

fail:
  ((void (*)(int *))0x848c0)(ep);
  tc_listening_ep = 0;
}

/*
 * telnet_console_dispose — shut down the telnet server.
 *
 * Closes the listening endpoint and any connected client, then zeros the
 * entire globals block so the subsystem is in a clean uninitialized state.
 */
void telnet_console_dispose(void)
{
  if (tc_initialized) {
    if (tc_listening_ep != 0) {
      ((void (*)(int *))0x848c0)(tc_listening_ep);
    }
    if (tc_client0_ep != 0) {
      ((void (*)(int *))0x848c0)(tc_client0_ep);
    }
  }
  csmemset((void *)0x46eee0, 0, 0x8c);
}

/*
 * telnet_console_process — per-tick I/O pump for the telnet console.
 *
 * Called once per game tick.  Two independent sections:
 *
 * 1. Accept section: if the listening endpoint is readable, attempt to
 *    accept a new connection.  If accepted and a free client slot exists,
 *    send a greeting and record the endpoint.  If all slots are occupied,
 *    send a rejection message and close the new connection.
 *
 * 2. Receive section: if the connected client's endpoint is readable,
 *    recv up to 0x20 bytes and dispatch to FUN_00130b70 (the per-character
 *    input handler, which echoes chars and processes CR/LF as commands).
 *    On recv error or handler failure, log and close the client.
 *
 * Note: FUN_00130b70 (0x130b70) reads ESI as an implicit register argument
 * pointing to the client slot struct at 0x46eee4.  It cannot be expressed
 * as a plain C function pointer.  The call uses inline asm to load ESI
 * before the call and pass the two stack arguments via "r" constraints
 * (safe — no "m" constraints with pushl, per project convention).
 */
void telnet_console_process(void)
{
  int slot;
  int *new_ep;
  int *slot_ep;
  char readable;
  int recv_result;
  char recv_buf[0x20];
  char input_ok;
  char *error_str;

  if (!tc_initialized) {
    return;
  }

  /* --- Accept section --- */
  readable = ((char (*)(int *, uint16_t))0x83040)(tc_listening_ep, 0);
  if (readable) {
    new_ep = ((int *(*)(int *))0x84450)(tc_listening_ep);
    if (new_ep != 0) {
      /* Search for a free client slot (max 1). */
      for (slot = 0; slot < TELNET_CONSOLE_MAX_CLIENTS; slot++) {
        if (*(int *)(0x46eee4 + slot * 0x84) == 0) {
          /* Found a free slot — send greeting. */
          const char *greeting = "Would you like to play a game?\r\n";
          int greet_len = csstrlen(greeting);
          int sent = ((int (*)(int *, const char *, int))0x82f50)(
            new_ep, greeting, greet_len);
          if (sent < 1) {
            /* Send failed; reject the connection. */
            ((void (*)(int *))0x848c0)(new_ep);
          } else {
            /* Store the accepted endpoint and clear the input buffer. */
            *(int *)(0x46eee4 + slot * 0x84) = (int)new_ep;
            *(char *)(0x46eee8 + slot * 0x84) = 0;
          }
          goto accept_done;
        }
      }
      /* No free slot — send rejection and close. */
      {
        const char *full_msg =
          "sorry - the maximum number of clients are already connected."
          " goodbye!\r\n";
        int full_len = csstrlen(full_msg);
        ((int (*)(int *, const char *, int))0x82f50)(new_ep, full_msg,
                                                     full_len);
        ((void (*)(int *))0x848c0)(new_ep);
      }
    accept_done:;
    }
  }

  /* --- Receive section (client slot 0 only) --- */
  slot_ep = tc_client0_ep;
  if (slot_ep == 0) {
    return;
  }
  readable = ((char (*)(int *, uint16_t))0x83040)(slot_ep, 0);
  if (!readable) {
    return;
  }

  recv_result = ((int (*)(int *, char *, int))0x82e50)(slot_ep, recv_buf, 0x20);
  if (recv_result > 0) {
    /* Dispatch received bytes to the telnet input handler.
     * FUN_00130b70 reads ESI as a pointer to the client slot struct
     * (0x46eee4).  Use inline asm to set ESI before the call. */
    int _buf = (int)recv_buf;
    int _len = recv_result;
    int _esi = 0x46eee4;
    asm volatile("pushl %[len]\n\t"
                 "pushl %[buf]\n\t"
                 "call *%[fn]\n\t"
                 "addl $8, %%esp"
                 : "=a"(input_ok)
                 : [fn] "r"((void *)0x130b70), [buf] "r"(_buf), [len] "r"(_len),
                   [esi] "S"(_esi)
                 : "ecx", "edx", "memory", "cc");
    if (input_ok) {
      return;
    }
    error(2, "error processing telnet client");
  } else {
    /* recv returned <= 0 — connection lost or error. */
    error_str = ((char *(*)(int16_t))0x81c80)((int16_t)recv_result);
    error(2, "connection lost to telnet client ('%s')", error_str);
  }

  /* Close and nullify the client on any error or graceful disconnect. */
  if (tc_client0_ep != 0) {
    ((void (*)(int *))0x848c0)(tc_client0_ep);
    tc_client0_ep = 0;
  }
}
/* --- telnet_console.obj batch drafts (2026-07-26) --- */

/* FUN_00130ec0 (0x130ec0) — readable C lift. */
void FUN_00130ec0(void)
{
  void *p = game_state_data_new(0x29a9e0, 0xc, 0x2bc);
  *(void **)0x5a90d4 = p;
  if (p == NULL)
    error(p, 0x29a9bc);
}

/* FUN_00130ef0 (0x130ef0) — readable C lift. */
void FUN_00130ef0(void)
{
  data_delete_all(*(data_t **)0x5a90d4);
}

/* FUN_00130f00 (0x130f00) — readable C lift. */
void FUN_00130f00(void)
{
  data_make_invalid(*(data_t **)0x5a90d4);
}

/* FUN_00130f10 (0x130f10) — readable C lift. */
void FUN_00130f10(void)
{
  if (*(int *)0x5a90d4 != 0) {
    *(int *)0x5a90d4 = 0;
  }
}

/* FUN_00130f30 (0x130f30) — XBE naked draft (batch 115). */
#if defined(__clang__)
static void *(*const b130f30_tag)(int, int) = tag_get;
static int (*const b130f30_c119610)(data_t *data) = data_new_at_index;
static void *(*const b130f30_dget)(void *, int) = (void *(*)(void *, int))datum_get;
static void *(*const b130f30_elem)(void *, int, int) = tag_block_get_element;
static void * (*const b130f30_c76ff0)(int tag_index, short bitmap_index) = FUN_00076ff0;

__attribute__((naked, noinline))
void FUN_00130f30(void)
{
  __asm__ volatile(
      "pushl %%ebp\n\t"
      "movl %%esp, %%ebp\n\t"
      "subl $0x20, %%esp\n\t"
      "movl 0x8(%%ebp), %%ecx\n\t"
      "orl $0xffffffff, %%eax\n\t"
      "cmpl $-1, %%ecx\n\t"
      "pushl %%esi\n\t"
      "je .LFUN_00130f30_6\n\t"
      "pushl %%ecx\n\t"
      "pushl $0x616e7421\n\t"
      "call *%[tag]\n\t"
      "movl %%eax, -0x4(%%ebp)\n\t"
      "movl 0x5a90d4, %%eax\n\t"
      "pushl %%eax\n\t"
      "call *%[c119610]\n\t"
      "movl %%eax, %%esi\n\t"
      "addl $0xc, %%esp\n\t"
      "cmpl $-1, %%esi\n\t"
      "movl %%esi, -0x14(%%ebp)\n\t"
      "je .LFUN_00130f30_5\n\t"
      "movl 0x5a90d4, %%ecx\n\t"
      "pushl %%ebx\n\t"
      "pushl %%edi\n\t"
      "pushl %%esi\n\t"
      "pushl %%ecx\n\t"
      "call *%[dget]\n\t"
      "movl 0x8(%%ebp), %%ecx\n\t"
      "movl %%eax, %%edi\n\t"
      "movl -0x4(%%ebp), %%eax\n\t"
      "xorl %%ebx, %%ebx\n\t"
      "addl $0xc4, %%eax\n\t"
      "movb %%bl, 0x4(%%edi)\n\t"
      "movl (%%eax), %%edx\n\t"
      "addl $8, %%esp\n\t"
      "cmpl $2, %%edx\n\t"
      "setl %%dl\n\t"
      "movl %%ecx, 0x8(%%edi)\n\t"
      "movl %%ebx, %%ecx\n\t"
      "movb %%dl, 0x5(%%edi)\n\t"
      "movl $0xffffffff, 0xc(%%edi)\n\t"
      "movw %%bx, 0x6(%%edi)\n\t"
      "movl %%ebx, 0x18(%%edi)\n\t"
      "movl %%ebx, 0x14(%%edi)\n\t"
      "movl %%ebx, 0x10(%%edi)\n\t"
      "movl %%ecx, -0x1c(%%ebp)\n\t"
      "cmpl %%ebx, (%%eax)\n\t"
      "movl %%ebx, %%edx\n\t"
      "movl %%edx, -0x20(%%ebp)\n\t"
      "movl %%edx, -0x18(%%ebp)\n\t"
      "movl %%ebx, -0x8(%%ebp)\n\t"
      "jle .LFUN_00130f30_4\n\t"
      "xorl %%eax, %%eax\n\t"
      ".LFUN_00130f30_1:\n\t"
      "movl %%eax, %%ecx\n\t"
      "pushl $0x80\n\t"
      "pushl %%eax\n\t"
      "movl -0x4(%%ebp), %%eax\n\t"
      "addl $0xc4, %%eax\n\t"
      "shll $5, %%ecx\n\t"
      "pushl %%eax\n\t"
      "leal 0x1c(%%ecx,%%edi,1), %%esi\n\t"
      "call *%[elem]\n\t"
      "movl -0x20(%%ebp), %%ecx\n\t"
      "movl %%esi, %%edx\n\t"
      "movl %%ecx, (%%edx)\n\t"
      "movl -0x1c(%%ebp), %%ecx\n\t"
      "movl %%ecx, 0x4(%%edx)\n\t"
      "movl -0x18(%%ebp), %%ecx\n\t"
      "movl %%ecx, 0x8(%%edx)\n\t"
      "movl -0x4(%%ebp), %%edx\n\t"
      "movl %%ebx, 0x14(%%esi)\n\t"
      "movl %%ebx, 0x10(%%esi)\n\t"
      "movl %%ebx, 0xc(%%esi)\n\t"
      "movw %%bx, 0x1c(%%esi)\n\t"
      "movl %%ebx, 0x18(%%esi)\n\t"
      "movl 0x2c(%%edx), %%ecx\n\t"
      "addl $0xc, %%esp\n\t"
      "cmpl $-1, %%ecx\n\t"
      "movl %%eax, 0x8(%%ebp)\n\t"
      "je .LFUN_00130f30_3\n\t"
      "pushl %%ecx\n\t"
      "pushl $0x6269746d\n\t"
      "call *%[tag]\n\t"
      "movl 0x8(%%ebp), %%ecx\n\t"
      "movw 0x28(%%ecx), %%cx\n\t"
      "addl $8, %%esp\n\t"
      "cmpw %%bx, %%cx\n\t"
      "movl %%eax, -0x10(%%ebp)\n\t"
      "jl .LFUN_00130f30_2\n\t"
      "movl 0x54(%%eax), %%edx\n\t"
      "addl $0x54, %%eax\n\t"
      "movswl %%cx, %%ecx\n\t"
      "cmpl %%edx, %%ecx\n\t"
      "jge .LFUN_00130f30_2\n\t"
      "pushl $0x40\n\t"
      "pushl %%ecx\n\t"
      "pushl %%eax\n\t"
      "call *%[elem]\n\t"
      "movl 0x34(%%eax), %%ecx\n\t"
      "addl $0x34, %%eax\n\t"
      "addl $0xc, %%esp\n\t"
      "cmpl %%ebx, %%ecx\n\t"
      "je .LFUN_00130f30_2\n\t"
      "pushl $0x20\n\t"
      "pushl %%ebx\n\t"
      "pushl %%eax\n\t"
      "call *%[elem]\n\t"
      "xorl %%edx, %%edx\n\t"
      "movw (%%eax), %%dx\n\t"
      "movl %%eax, -0xc(%%ebp)\n\t"
      "movl -0x4(%%ebp), %%eax\n\t"
      "movl 0x2c(%%eax), %%ecx\n\t"
      "pushl %%edx\n\t"
      "pushl %%ecx\n\t"
      "call *%[c76ff0]\n\t"
      "addl $0x14, %%esp\n\t"
      "cmpl %%ebx, %%eax\n\t"
      "je .LFUN_00130f30_2\n\t"
      "movl -0xc(%%ebp), %%ecx\n\t"
      "movswl 0x4(%%eax), %%edx\n\t"
      "flds 0xc(%%ecx)\n\t"
      "fsubs 0x8(%%ecx)\n\t"
      "movl -0x10(%%ebp), %%eax\n\t"
      "movswl 0x50(%%eax), %%ecx\n\t"
      "movl %%edx, -0xc(%%ebp)\n\t"
      "movl 0x8(%%ebp), %%edx\n\t"
      "movl %%ecx, -0x10(%%ebp)\n\t"
      "fimull -0xc(%%ebp)\n\t"
      "fildl -0x10(%%ebp)\n\t"
      ".byte 0xdc, 0xc0\n\t"
      ".byte 0xde, 0xe9\n\t"
      "fsubs 0x2533c8\n\t"
      "fdivrs 0x24(%%edx)\n\t"
      "fstps 0x18(%%esi)\n\t"
      ".LFUN_00130f30_2:\n\t"
      "movl 0x8(%%ebp), %%eax\n\t"
      ".LFUN_00130f30_3:\n\t"
      "flds -0x20(%%ebp)\n\t"
      "movl -0x4(%%ebp), %%ecx\n\t"
      "fadds 0x74(%%eax)\n\t"
      "movl 0xc4(%%ecx), %%edx\n\t"
      "addl $0xc4, %%ecx\n\t"
      "fstps -0x20(%%ebp)\n\t"
      "flds -0x1c(%%ebp)\n\t"
      "fadds 0x78(%%eax)\n\t"
      "fstps -0x1c(%%ebp)\n\t"
      "flds -0x18(%%ebp)\n\t"
      "fadds 0x7c(%%eax)\n\t"
      "movl -0x8(%%ebp), %%eax\n\t"
      "incl %%eax\n\t"
      "movl %%eax, -0x8(%%ebp)\n\t"
      "movswl %%ax, %%eax\n\t"
      "fstps -0x18(%%ebp)\n\t"
      "cmpl %%edx, %%eax\n\t"
      "jl .LFUN_00130f30_1\n\t"
      "movl -0x14(%%ebp), %%esi\n\t"
      ".LFUN_00130f30_4:\n\t"
      "movswl -0x8(%%ebp), %%eax\n\t"
      "movl -0x20(%%ebp), %%edx\n\t"
      "shll $5, %%eax\n\t"
      "leal 0x1c(%%eax,%%edi,1), %%edi\n\t"
      "movl -0x1c(%%ebp), %%eax\n\t"
      "movl %%edi, %%ecx\n\t"
      "movl %%edx, (%%ecx)\n\t"
      "movl -0x18(%%ebp), %%edx\n\t"
      "movl %%ebx, 0x14(%%edi)\n\t"
      "movl %%ebx, 0x10(%%edi)\n\t"
      "movl %%ebx, 0xc(%%edi)\n\t"
      "movl %%eax, 0x4(%%ecx)\n\t"
      "popl %%edi\n\t"
      "movl %%edx, 0x8(%%ecx)\n\t"
      "popl %%ebx\n\t"
      ".LFUN_00130f30_5:\n\t"
      "movl %%esi, %%eax\n\t"
      ".LFUN_00130f30_6:\n\t"
      "popl %%esi\n\t"
      "movl %%ebp, %%esp\n\t"
      "popl %%ebp\n\t"
      "ret\n\t"
      :
      : [tag] "m"(b130f30_tag), [c119610] "m"(b130f30_c119610), [dget] "m"(b130f30_dget), [elem] "m"(b130f30_elem), [c76ff0] "m"(b130f30_c76ff0)
      : "memory");
}
#else
#error "FUN_00130f30: clang naked draft required"
#endif


/* FUN_00131130 (0x131130) — readable C lift. */
void FUN_00131130(int handle)
{
  datum_delete(*(data_t **)0x5a90d4, handle);
}

/* FUN_00131150 (0x131150) — XBE naked draft (batch 125). */
#if defined(__clang__)
static short (*const b131150_markers)(int, void *, void *, int) = object_get_markers_by_string_id;
static void (*const b131150_c18f180)(void *location_out, void *point) = scenario_location_from_point;
static void (*const b131150_ftol)(void) = FUN_001d9068;

__attribute__((naked, noinline))
void FUN_00131150(void)
{
  __asm__ volatile(
      "pushl %%ebp\n\t"
      "movl %%esp, %%ebp\n\t"
      "subl $0x80, %%esp\n\t"
      "movl 0x8(%%ebp), %%ecx\n\t"
      "movl 0xc(%%esi), %%edx\n\t"
      "pushl %%ebx\n\t"
      "movl %%eax, %%ebx\n\t"
      "pushl $1\n\t"
      "leal -0x80(%%ebp), %%eax\n\t"
      "pushl %%eax\n\t"
      "pushl %%ecx\n\t"
      "pushl %%edx\n\t"
      "call *%[markers]\n\t"
      "movl -0x20(%%ebp), %%ecx\n\t"
      "movl -0x1c(%%ebp), %%edx\n\t"
      "movl %%edi, %%eax\n\t"
      "movl %%ecx, (%%eax)\n\t"
      "movl -0x18(%%ebp), %%ecx\n\t"
      "movl %%edx, 0x4(%%eax)\n\t"
      "movl -0x44(%%ebp), %%edx\n\t"
      "movl %%ecx, 0x8(%%eax)\n\t"
      "movl -0x40(%%ebp), %%eax\n\t"
      "movl -0x3c(%%ebp), %%ecx\n\t"
      "movl %%edx, (%%ebx)\n\t"
      "movl %%eax, 0x4(%%ebx)\n\t"
      "movl 0xc(%%ebp), %%eax\n\t"
      "leal -0x20(%%ebp), %%edx\n\t"
      "pushl %%edx\n\t"
      "pushl %%eax\n\t"
      "movl %%ecx, 0x8(%%ebx)\n\t"
      "call *%[c18f180]\n\t"
      "flds (%%edi)\n\t"
      "fsubs 0x10(%%esi)\n\t"
      "leal 0x10(%%esi), %%ebx\n\t"
      "addl $0x18, %%esp\n\t"
      "movl %%ebx, -0x8(%%ebp)\n\t"
      "fstps -0x14(%%ebp)\n\t"
      "flds 0x4(%%edi)\n\t"
      "fsubs 0x14(%%esi)\n\t"
      "fstps -0x10(%%ebp)\n\t"
      "flds 0x8(%%edi)\n\t"
      "fsubs 0x18(%%esi)\n\t"
      "fstps -0xc(%%ebp)\n\t"
      "flds -0x14(%%ebp)\n\t"
      "call *%[ftol]\n\t"
      "cdq\n\t"
      "xorl %%edx, %%eax\n\t"
      "subl %%edx, %%eax\n\t"
      "movl %%eax, -0x4(%%ebp)\n\t"
      "fildl -0x4(%%ebp)\n\t"
      "fcomps 0x2533c8\n\t"
      "fnstsw %%ax\n\t"
      "testb $0x41, %%ah\n\t"
      "je .LFUN_00131150_1\n\t"
      "flds -0x10(%%ebp)\n\t"
      "call *%[ftol]\n\t"
      "cdq\n\t"
      "xorl %%edx, %%eax\n\t"
      "subl %%edx, %%eax\n\t"
      "movl %%eax, -0x4(%%ebp)\n\t"
      "fildl -0x4(%%ebp)\n\t"
      "fcomps 0x2533c8\n\t"
      "fnstsw %%ax\n\t"
      "testb $0x41, %%ah\n\t"
      "je .LFUN_00131150_1\n\t"
      "flds -0xc(%%ebp)\n\t"
      "call *%[ftol]\n\t"
      "cdq\n\t"
      "xorl %%edx, %%eax\n\t"
      "subl %%edx, %%eax\n\t"
      "movl %%eax, -0x4(%%ebp)\n\t"
      "fildl -0x4(%%ebp)\n\t"
      "fcomps 0x2533c8\n\t"
      "fnstsw %%ax\n\t"
      "testb $0x41, %%ah\n\t"
      "jne .LFUN_00131150_3\n\t"
      ".LFUN_00131150_1:\n\t"
      "movl 0x8(%%ebp), %%edx\n\t"
      "movl 0xc4(%%edx), %%eax\n\t"
      "xorl %%ecx, %%ecx\n\t"
      "incl %%eax\n\t"
      "testl %%eax, %%eax\n\t"
      "jle .LFUN_00131150_3\n\t"
      "xorl %%eax, %%eax\n\t"
      ".LFUN_00131150_2:\n\t"
      "flds -0x14(%%ebp)\n\t"
      "shll $5, %%eax\n\t"
      "fadds 0x1c(%%eax,%%esi,1)\n\t"
      "leal 0x1c(%%eax,%%esi,1), %%eax\n\t"
      "incl %%ecx\n\t"
      "fstps (%%eax)\n\t"
      "flds -0x10(%%ebp)\n\t"
      "fadds 0x4(%%eax)\n\t"
      "fstps 0x4(%%eax)\n\t"
      "flds -0xc(%%ebp)\n\t"
      "fadds 0x8(%%eax)\n\t"
      "fstps 0x8(%%eax)\n\t"
      "movl 0xc4(%%edx), %%ebx\n\t"
      "movswl %%cx, %%eax\n\t"
      "incl %%ebx\n\t"
      "cmpl %%ebx, %%eax\n\t"
      "jl .LFUN_00131150_2\n\t"
      "movl -0x8(%%ebp), %%ebx\n\t"
      ".LFUN_00131150_3:\n\t"
      "movl (%%edi), %%ecx\n\t"
      "movl %%ecx, (%%ebx)\n\t"
      "movl 0x4(%%edi), %%edx\n\t"
      "movl %%edx, 0x4(%%ebx)\n\t"
      "movl 0x8(%%edi), %%eax\n\t"
      "movl %%eax, 0x8(%%ebx)\n\t"
      "popl %%ebx\n\t"
      "movl %%ebp, %%esp\n\t"
      "popl %%ebp\n\t"
      "ret\n\t"
      :
      : [markers] "m"(b131150_markers), [c18f180] "m"(b131150_c18f180), [ftol] "m"(b131150_ftol)
      : "memory");
}
#else
#error "FUN_00131150: clang naked draft required"
#endif


/* FUN_00131280 (0x131280) — XBE naked draft (batch 123). */
#if defined(__clang__)
static void (*const b131280_c18d2c0)(uint32_t *param_1, int16_t param_2, uint32_t param_3, int param_4, uint32_t param_5) = FUN_0018d2c0;
static void *(*const b131280_elem)(void *, int, int) = tag_block_get_element;
static void (*const b131280_c18d6e0)(void *data, int16_t mode, int16_t sequence_index, int16_t sprite_index, float *untransformed_origin, float *untransformed_direction, float angle, float scale, float *color, float intensity, uint32_t flags) = FUN_0018d6e0;
static void (*const b131280_c18d360)(void *sprite_build_data) = FUN_0018d360;

__attribute__((naked, noinline))
void FUN_00131280(void)
{
  __asm__ volatile(
      "pushl %%ebp\n\t"
      "movl %%esp, %%ebp\n\t"
      "subl $0xc8, %%esp\n\t"
      "movl 0xc4(%%ecx), %%eax\n\t"
      "testl %%eax, %%eax\n\t"
      "pushl %%ebx\n\t"
      "leal 0xc4(%%ecx), %%ebx\n\t"
      "je .LFUN_00131280_6\n\t"
      "flds 0x253f00\n\t"
      "fsubs 0x98(%%ecx)\n\t"
      "flds 0x94(%%ecx)\n\t"
      "fsubs 0x98(%%ecx)\n\t"
      ".byte 0xde, 0xf9\n\t"
      "fsts -0x4(%%ebp)\n\t"
      "fcomps 0x2533c0\n\t"
      "fnstsw %%ax\n\t"
      "testb $5, %%ah\n\t"
      "jp .LFUN_00131280_1\n\t"
      "movl $0, -0x4(%%ebp)\n\t"
      "jmp .LFUN_00131280_2\n\t"
      ".LFUN_00131280_1:\n\t"
      "flds -0x4(%%ebp)\n\t"
      "fcomps 0x2533c8\n\t"
      "fnstsw %%ax\n\t"
      "testb $0x41, %%ah\n\t"
      "jne .LFUN_00131280_2\n\t"
      "movl $0x3f800000, -0x4(%%ebp)\n\t"
      ".LFUN_00131280_2:\n\t"
      "movl 0x2c(%%ecx), %%eax\n\t"
      "xorl %%ecx, %%ecx\n\t"
      "movw (%%ebx), %%cx\n\t"
      "pushl $0\n\t"
      "pushl $0x326b30\n\t"
      "pushl %%eax\n\t"
      "leal -0xc8(%%ebp), %%edx\n\t"
      "pushl %%ecx\n\t"
      "pushl %%edx\n\t"
      "call *%[c18d2c0]\n\t"
      "movl (%%ebx), %%eax\n\t"
      "addl $0x14, %%esp\n\t"
      "testl %%eax, %%eax\n\t"
      "movl $0, -0x8(%%ebp)\n\t"
      "jle .LFUN_00131280_5\n\t"
      "pushl %%esi\n\t"
      "xorl %%eax, %%eax\n\t"
      "pushl %%edi\n\t"
      "leal (%%ecx), %%ecx\n\t"
      ".LFUN_00131280_3:\n\t"
      "movl 0x8(%%ebp), %%edx\n\t"
      "movl %%eax, %%ecx\n\t"
      "pushl $0x80\n\t"
      "shll $5, %%ecx\n\t"
      "pushl %%eax\n\t"
      "leal (%%ecx,%%edx,1), %%edi\n\t"
      "pushl %%ebx\n\t"
      "leal 0x1c(%%edi), %%esi\n\t"
      "call *%[elem]\n\t"
      "flds 0x3c(%%edi)\n\t"
      "fsubs (%%esi)\n\t"
      "movl %%eax, %%ecx\n\t"
      "leal 0x2c(%%ecx), %%eax\n\t"
      "addl $0xc, %%esp\n\t"
      "fstps -0x14(%%ebp)\n\t"
      "flds 0x40(%%edi)\n\t"
      "fsubs 0x4(%%esi)\n\t"
      "fstps -0x10(%%ebp)\n\t"
      "flds 0x44(%%edi)\n\t"
      "fsubs 0x8(%%esi)\n\t"
      "fstps -0xc(%%ebp)\n\t"
      "movl (%%eax), %%edx\n\t"
      "flds 0x18(%%esi)\n\t"
      "movl %%edx, -0x24(%%ebp)\n\t"
      "movl 0x4(%%eax), %%edx\n\t"
      "fcomps 0x2533c0\n\t"
      "movl %%edx, -0x20(%%ebp)\n\t"
      "movl 0x8(%%eax), %%edx\n\t"
      "movl %%edx, -0x1c(%%ebp)\n\t"
      "movl 0xc(%%eax), %%eax\n\t"
      "movl %%eax, -0x18(%%ebp)\n\t"
      "fnstsw %%ax\n\t"
      "testb $0x44, %%ah\n\t"
      "jnp .LFUN_00131280_4\n\t"
      "flds -0x4(%%ebp)\n\t"
      "fcomps 0x2533c0\n\t"
      "fnstsw %%ax\n\t"
      "testb $0x41, %%ah\n\t"
      "jne .LFUN_00131280_4\n\t"
      "movl -0x4(%%ebp), %%edx\n\t"
      "movswl 0x28(%%ecx), %%ecx\n\t"
      "pushl $0\n\t"
      "pushl %%edx\n\t"
      "movl 0x18(%%esi), %%edx\n\t"
      "leal -0x24(%%ebp), %%eax\n\t"
      "pushl %%eax\n\t"
      "pushl %%edx\n\t"
      "pushl $0\n\t"
      "leal -0x14(%%ebp), %%eax\n\t"
      "pushl %%eax\n\t"
      "pushl %%esi\n\t"
      "pushl $0\n\t"
      "pushl %%ecx\n\t"
      "leal -0xc8(%%ebp), %%edx\n\t"
      "pushl $1\n\t"
      "pushl %%edx\n\t"
      "call *%[c18d6e0]\n\t"
      "addl $0x2c, %%esp\n\t"
      ".LFUN_00131280_4:\n\t"
      "movl -0x8(%%ebp), %%eax\n\t"
      "movl (%%ebx), %%ecx\n\t"
      "incl %%eax\n\t"
      "movl %%eax, -0x8(%%ebp)\n\t"
      "movswl %%ax, %%eax\n\t"
      "cmpl %%ecx, %%eax\n\t"
      "jl .LFUN_00131280_3\n\t"
      "popl %%edi\n\t"
      "popl %%esi\n\t"
      ".LFUN_00131280_5:\n\t"
      "leal -0xc8(%%ebp), %%eax\n\t"
      "pushl %%eax\n\t"
      "call *%[c18d360]\n\t"
      "addl $4, %%esp\n\t"
      ".LFUN_00131280_6:\n\t"
      "popl %%ebx\n\t"
      "movl %%ebp, %%esp\n\t"
      "popl %%ebp\n\t"
      "ret\n\t"
      :
      : [c18d2c0] "m"(b131280_c18d2c0), [elem] "m"(b131280_elem), [c18d6e0] "m"(b131280_c18d6e0), [c18d360] "m"(b131280_c18d360)
      : "memory");
}
#else
#error "FUN_00131280: clang naked draft required"
#endif


/* FUN_001313f0 (0x1313f0) — XBE naked draft (batch 110). */
#if defined(__clang__)
static void (*const b1313f0_c131150)(void) = FUN_00131150;
static void *(*const b1313f0_elem)(void *, int, int) = tag_block_get_element;
static void *(*const b1313f0_tag)(int, int) = tag_get;
static int (*const b1313f0_c154a50)(int flags, int physics_tag_data, int *collision_location, int object_handle, float *position, float *velocity, float *force, float *collision_normal_out, int16_t *surface_index_out, float radius, float delta_time) = FUN_00154a50;
static float (*const b1313f0_norm)(float *) = normalize3d;
static float (*const b1313f0_c10c510)(float *v1, float *v2) = FUN_0010c510;
static void (*const b1313f0_rots)(float *, float *, float, float) = rotate_vector3d_by_sincos;

__attribute__((naked, noinline))
void FUN_001313f0(void)
{
  __asm__ volatile(
      "pushl %%ebp\n\t"
      "movl %%esp, %%ebp\n\t"
      "subl $0x98, %%esp\n\t"
      "movl 0xc(%%ebp), %%ecx\n\t"
      "pushl %%esi\n\t"
      "movl 0x8(%%ebp), %%esi\n\t"
      "pushl %%edi\n\t"
      "leal -0x8c(%%ebp), %%eax\n\t"
      "pushl %%eax\n\t"
      "pushl %%ecx\n\t"
      "leal -0x84(%%ebp), %%eax\n\t"
      "leal -0x60(%%ebp), %%edi\n\t"
      "call *%[c131150]\n\t"
      "movb 0x5(%%esi), %%al\n\t"
      "addl $8, %%esp\n\t"
      "testb %%al, %%al\n\t"
      "jne .LFUN_001313f0_7\n\t"
      "flds 0x10(%%ebp)\n\t"
      "fcomps 0x2533c0\n\t"
      "fnstsw %%ax\n\t"
      "testb $0x41, %%ah\n\t"
      "jne .LFUN_001313f0_7\n\t"
      "movl 0xc(%%ebp), %%eax\n\t"
      "movl 0xc4(%%eax), %%ecx\n\t"
      "addl $0xc4, %%eax\n\t"
      "pushl %%ebx\n\t"
      "leal 0x1(%%ecx), %%edx\n\t"
      "xorl %%ebx, %%ebx\n\t"
      "testl %%edx, %%edx\n\t"
      "jle .LFUN_001313f0_6\n\t"
      "flds 0x2533c8\n\t"
      "xorl %%eax, %%eax\n\t"
      "fdivs 0x10(%%ebp)\n\t"
      "fstps -0x14(%%ebp)\n\t"
      ".LFUN_001313f0_1:\n\t"
      "movl 0x8(%%ebp), %%esi\n\t"
      "movl %%eax, %%edx\n\t"
      "shll $5, %%edx\n\t"
      "cmpl %%ecx, %%eax\n\t"
      "leal 0x1c(%%edx,%%esi,1), %%edi\n\t"
      "jne .LFUN_001313f0_2\n\t"
      "leal -0x1(%%ecx), %%eax\n\t"
      ".LFUN_001313f0_2:\n\t"
      "pushl $0x80\n\t"
      "pushl %%eax\n\t"
      "movl 0xc(%%ebp), %%eax\n\t"
      "addl $0xc4, %%eax\n\t"
      "pushl %%eax\n\t"
      "call *%[elem]\n\t"
      "movl %%eax, %%esi\n\t"
      "flds (%%esi)\n\t"
      "movl 0xc(%%ebp), %%eax\n\t"
      "fmuls 0x90(%%eax)\n\t"
      "addl $0xc, %%esp\n\t"
      "incw 0x1c(%%edi)\n\t"
      "testw %%bx, %%bx\n\t"
      "fstps -0x10(%%ebp)\n\t"
      "jne .LFUN_001313f0_3\n\t"
      "movl -0x60(%%ebp), %%eax\n\t"
      "movl -0x5c(%%ebp), %%ecx\n\t"
      "movl -0x58(%%ebp), %%edx\n\t"
      "movl %%eax, -0xc(%%ebp)\n\t"
      "movl -0x84(%%ebp), %%eax\n\t"
      "movl %%ecx, -0x8(%%ebp)\n\t"
      "movl -0x80(%%ebp), %%ecx\n\t"
      "movl %%edx, -0x4(%%ebp)\n\t"
      "movl -0x7c(%%ebp), %%edx\n\t"
      "movl %%eax, -0x20(%%ebp)\n\t"
      "movl %%ecx, -0x1c(%%ebp)\n\t"
      "movl %%edx, -0x18(%%ebp)\n\t"
      "jmp .LFUN_001313f0_4\n\t"
      ".LFUN_001313f0_3:\n\t"
      "movl %%edi, %%ecx\n\t"
      "movl (%%ecx), %%edx\n\t"
      "movl %%edx, -0xc(%%ebp)\n\t"
      "movl 0x4(%%ecx), %%edx\n\t"
      "movl 0x8(%%ecx), %%ecx\n\t"
      "movl %%edx, -0x8(%%ebp)\n\t"
      "movl 0x10(%%ebp), %%edx\n\t"
      "pushl %%edx\n\t"
      "pushl $0x3ca3d70a\n\t"
      "pushl $0\n\t"
      "pushl $0\n\t"
      "pushl $0\n\t"
      "movl %%ecx, -0x4(%%ebp)\n\t"
      "leal 0xc(%%edi), %%ecx\n\t"
      "pushl %%ecx\n\t"
      "leal -0xc(%%ebp), %%edx\n\t"
      "pushl %%edx\n\t"
      "movl 0x3c(%%eax), %%edx\n\t"
      "pushl $-1\n\t"
      "leal -0x8c(%%ebp), %%ecx\n\t"
      "pushl %%ecx\n\t"
      "pushl %%edx\n\t"
      "pushl $0x70706879\n\t"
      "call *%[tag]\n\t"
      "addl $8, %%esp\n\t"
      "pushl %%eax\n\t"
      "pushl $0\n\t"
      "call *%[c154a50]\n\t"
      "flds -0xc(%%ebp)\n\t"
      "fsubs -0x30(%%ebp)\n\t"
      "addl $0x2c, %%esp\n\t"
      "flds -0x8(%%ebp)\n\t"
      "fsubs -0x2c(%%ebp)\n\t"
      "flds -0x4(%%ebp)\n\t"
      "fsubs -0x28(%%ebp)\n\t"
      "fsts -0x64(%%ebp)\n\t"
      "fmuls -0x64(%%ebp)\n\t"
      "fld %%st(1)\n\t"
      ".byte 0xd8, 0xca\n\t"
      ".byte 0xde, 0xc1\n\t"
      "fld %%st(2)\n\t"
      ".byte 0xd8, 0xcb\n\t"
      ".byte 0xde, 0xc1\n\t"
      "fsqrt\n\t"
      "fdivrs 0x24(%%esi)\n\t"
      "fsts -0x24(%%ebp)\n\t"
      ".byte 0xd8, 0xca\n\t"
      "fadds -0x30(%%ebp)\n\t"
      "fstps -0x98(%%ebp)\n\t"
      "flds -0x24(%%ebp)\n\t"
      ".byte 0xd8, 0xc9\n\t"
      "fadds -0x2c(%%ebp)\n\t"
      "fstp %%st(2)\n\t"
      "fstp %%st(0)\n\t"
      "flds -0x24(%%ebp)\n\t"
      "fmuls -0x64(%%ebp)\n\t"
      "fadds -0x28(%%ebp)\n\t"
      "flds 0x2533c8\n\t"
      "fsubs -0x10(%%ebp)\n\t"
      "flds -0x98(%%ebp)\n\t"
      ".byte 0xd8, 0xc9\n\t"
      "flds -0x54(%%ebp)\n\t"
      "fmuls -0x10(%%ebp)\n\t"
      ".byte 0xde, 0xc1\n\t"
      "fstps -0xc(%%ebp)\n\t"
      "fld %%st(0)\n\t"
      ".byte 0xd8, 0xcb\n\t"
      "flds -0x50(%%ebp)\n\t"
      "fmuls -0x10(%%ebp)\n\t"
      ".byte 0xde, 0xc1\n\t"
      "fstps -0x8(%%ebp)\n\t"
      ".byte 0xd8, 0xc9\n\t"
      "flds -0x4c(%%ebp)\n\t"
      "fmuls -0x10(%%ebp)\n\t"
      ".byte 0xde, 0xc1\n\t"
      "fstps -0x4(%%ebp)\n\t"
      "fstp %%st(0)\n\t"
      "fstp %%st(0)\n\t"
      "flds -0xc(%%ebp)\n\t"
      "fsubs -0x30(%%ebp)\n\t"
      "fstps -0x20(%%ebp)\n\t"
      "flds -0x8(%%ebp)\n\t"
      "fsubs -0x2c(%%ebp)\n\t"
      "fstps -0x1c(%%ebp)\n\t"
      "flds -0x4(%%ebp)\n\t"
      "fsubs -0x28(%%ebp)\n\t"
      "fstps -0x18(%%ebp)\n\t"
      ".LFUN_001313f0_4:\n\t"
      "flds -0x18(%%ebp)\n\t"
      "leal -0x3c(%%ebp), %%eax\n\t"
      "fmuls 0x2533c0\n\t"
      "pushl %%eax\n\t"
      "flds -0x1c(%%ebp)\n\t"
      "movl $0, -0x78(%%ebp)\n\t"
      "movl $0, -0x74(%%ebp)\n\t"
      ".byte 0xd8, 0xe9\n\t"
      "movl $0x3f800000, -0x70(%%ebp)\n\t"
      "fstps -0x3c(%%ebp)\n\t"
      "flds -0x20(%%ebp)\n\t"
      ".byte 0xd8, 0xe1\n\t"
      "fstps -0x38(%%ebp)\n\t"
      "fstp %%st(0)\n\t"
      "flds -0x1c(%%ebp)\n\t"
      "fmuls 0x2533c0\n\t"
      "flds -0x20(%%ebp)\n\t"
      "fmuls 0x2533c0\n\t"
      ".byte 0xde, 0xe9\n\t"
      "fstps -0x34(%%ebp)\n\t"
      "call *%[norm]\n\t"
      "fcomps 0x2533c0\n\t"
      "addl $4, %%esp\n\t"
      "fnstsw %%ax\n\t"
      "testb $0x44, %%ah\n\t"
      "jp .LFUN_001313f0_5\n\t"
      "movl 0x31fc40, %%ecx\n\t"
      "movl (%%ecx), %%edx\n\t"
      "movl %%edx, -0x3c(%%ebp)\n\t"
      "movl 0x4(%%ecx), %%eax\n\t"
      "movl %%eax, -0x38(%%ebp)\n\t"
      "movl 0x8(%%ecx), %%ecx\n\t"
      "movl %%ecx, -0x34(%%ebp)\n\t"
      ".LFUN_001313f0_5:\n\t"
      "addl $0x74, %%esi\n\t"
      "movl (%%esi), %%edx\n\t"
      "movl 0x4(%%esi), %%eax\n\t"
      "movl 0x8(%%esi), %%ecx\n\t"
      "movl %%edx, -0x48(%%ebp)\n\t"
      "leal -0x20(%%ebp), %%edx\n\t"
      "movl %%eax, -0x44(%%ebp)\n\t"
      "pushl %%edx\n\t"
      "leal -0x78(%%ebp), %%eax\n\t"
      "pushl %%eax\n\t"
      "movl %%ecx, -0x40(%%ebp)\n\t"
      "call *%[c10c510]\n\t"
      "fld %%st(0)\n\t"
      "fcos\n\t"
      "leal -0x3c(%%ebp), %%ecx\n\t"
      "leal -0x48(%%ebp), %%edx\n\t"
      "fstps 0x4(%%esp)\n\t"
      "fsin\n\t"
      "fstps (%%esp)\n\t"
      "pushl %%ecx\n\t"
      "pushl %%edx\n\t"
      "call *%[rots]\n\t"
      "flds -0x48(%%ebp)\n\t"
      "fadds -0xc(%%ebp)\n\t"
      "movl -0xc(%%ebp), %%eax\n\t"
      "movl -0x8(%%ebp), %%ecx\n\t"
      "movl -0x4(%%ebp), %%edx\n\t"
      "fstps -0x54(%%ebp)\n\t"
      "movl %%eax, -0x30(%%ebp)\n\t"
      "flds -0x44(%%ebp)\n\t"
      "addl $0x10, %%esp\n\t"
      "fadds -0x8(%%ebp)\n\t"
      "incl %%ebx\n\t"
      "movl %%ecx, -0x2c(%%ebp)\n\t"
      "movl %%edx, -0x28(%%ebp)\n\t"
      "fstps -0x50(%%ebp)\n\t"
      "flds -0x40(%%ebp)\n\t"
      "fadds -0x4(%%ebp)\n\t"
      "fstps -0x4c(%%ebp)\n\t"
      "flds -0xc(%%ebp)\n\t"
      "fsubs (%%edi)\n\t"
      "fmuls -0x14(%%ebp)\n\t"
      "fstps 0xc(%%edi)\n\t"
      "flds -0x8(%%ebp)\n\t"
      "fsubs 0x4(%%edi)\n\t"
      "fmuls -0x14(%%ebp)\n\t"
      "fstps 0x10(%%edi)\n\t"
      "flds -0x4(%%ebp)\n\t"
      "fsubs 0x8(%%edi)\n\t"
      "movl %%eax, (%%edi)\n\t"
      "movl 0xc(%%ebp), %%eax\n\t"
      "addl $0xc4, %%eax\n\t"
      "fmuls -0x14(%%ebp)\n\t"
      "movl %%ecx, 0x4(%%edi)\n\t"
      "movl %%edx, 0x8(%%edi)\n\t"
      "fstps 0x14(%%edi)\n\t"
      "movl (%%eax), %%ecx\n\t"
      "movswl %%bx, %%eax\n\t"
      "leal 0x1(%%ecx), %%edx\n\t"
      "cmpl %%edx, %%eax\n\t"
      "jl .LFUN_001313f0_1\n\t"
      ".LFUN_001313f0_6:\n\t"
      "popl %%ebx\n\t"
      ".LFUN_001313f0_7:\n\t"
      "popl %%edi\n\t"
      "popl %%esi\n\t"
      "movl %%ebp, %%esp\n\t"
      "popl %%ebp\n\t"
      "ret\n\t"
      :
      : [c131150] "m"(b1313f0_c131150), [elem] "m"(b1313f0_elem), [tag] "m"(b1313f0_tag), [c154a50] "m"(b1313f0_c154a50), [norm] "m"(b1313f0_norm), [c10c510] "m"(b1313f0_c10c510), [rots] "m"(b1313f0_rots)
      : "memory");
}
#else
#error "FUN_001313f0: clang naked draft required"
#endif


/* FUN_00131700 (0x131700) — XBE naked draft (batch 148). */
#if defined(__clang__)
static void *(*const b131700_get)(int, int) = object_get_and_verify_type;
static void *(*const b131700_dget)(void *, int) = (void *(*)(void *, int))datum_get;
static void *(*const b131700_tag)(int, int) = tag_get;
static void (*const b131700_c1313f0)(void) = FUN_001313f0;
static void (*const b131700_c131280)(void) = FUN_00131280;

__attribute__((naked, noinline))
void FUN_00131700(void)
{
  __asm__ volatile(
      "pushl %%ebp\n\t"
      "movl %%esp, %%ebp\n\t"
      "pushl %%ebx\n\t"
      "movl 0x8(%%ebp), %%ebx\n\t"
      "pushl %%esi\n\t"
      "pushl %%edi\n\t"
      "pushl $-1\n\t"
      "pushl %%ebx\n\t"
      "call *%[get]\n\t"
      "movl 0xc(%%ebp), %%eax\n\t"
      "movl 0x5a90d4, %%ecx\n\t"
      "pushl %%eax\n\t"
      "pushl %%ecx\n\t"
      "call *%[dget]\n\t"
      "movl %%eax, %%esi\n\t"
      "movl 0x8(%%esi), %%edx\n\t"
      "pushl %%edx\n\t"
      "pushl $0x616e7421\n\t"
      "call *%[tag]\n\t"
      "movl %%eax, %%edi\n\t"
      "movb 0x5(%%esi), %%al\n\t"
      "addl $0x18, %%esp\n\t"
      "testb %%al, %%al\n\t"
      "jne .LFUN_00131700_2\n\t"
      "cmpw $5, 0x6(%%esi)\n\t"
      "movl %%ebx, 0xc(%%esi)\n\t"
      "jle .LFUN_00131700_1\n\t"
      "pushl $0x3d4ccccd\n\t"
      "pushl %%edi\n\t"
      "pushl %%esi\n\t"
      "call *%[c1313f0]\n\t"
      "pushl $0x3d4ccccd\n\t"
      "pushl %%edi\n\t"
      "pushl %%esi\n\t"
      "call *%[c1313f0]\n\t"
      "pushl $0x3d4ccccd\n\t"
      "pushl %%edi\n\t"
      "pushl %%esi\n\t"
      "call *%[c1313f0]\n\t"
      "addl $0x24, %%esp\n\t"
      ".LFUN_00131700_1:\n\t"
      "pushl %%esi\n\t"
      "movl %%edi, %%ecx\n\t"
      "movw $0, 0x6(%%esi)\n\t"
      "call *%[c131280]\n\t"
      "addl $4, %%esp\n\t"
      ".LFUN_00131700_2:\n\t"
      "popl %%edi\n\t"
      "popl %%esi\n\t"
      "popl %%ebx\n\t"
      "popl %%ebp\n\t"
      "ret\n\t"
      :
      : [get] "m"(b131700_get), [dget] "m"(b131700_dget), [tag] "m"(b131700_tag), [c1313f0] "m"(b131700_c1313f0), [c131280] "m"(b131700_c131280)
      : "memory");
}
#else
#error "FUN_00131700: clang naked draft required"
#endif


/* FUN_00131790 (0x131790) — XBE naked draft (batch 142). */
#if defined(__clang__)
static int (*const b131790_c1198f0)(data_t *data, int prev_index) = data_next_index;
static void *(*const b131790_dget)(void *, int) = (void *(*)(void *, int))datum_get;
static void *(*const b131790_tag)(int, int) = tag_get;
static void (*const b131790_c1313f0)(void) = FUN_001313f0;

__attribute__((naked, noinline))
void FUN_00131790(void)
{
  __asm__ volatile(
      "pushl %%ebp\n\t"
      "movl %%esp, %%ebp\n\t"
      "pushl %%ecx\n\t"
      "movl 0x5a90d4, %%eax\n\t"
      "pushl %%edi\n\t"
      "pushl $-1\n\t"
      "pushl %%eax\n\t"
      "call *%[c1198f0]\n\t"
      "movl %%eax, %%edi\n\t"
      "addl $8, %%esp\n\t"
      "cmpl $-1, %%edi\n\t"
      "je .LFUN_00131790_5\n\t"
      "pushl %%esi\n\t"
      ".LFUN_00131790_1:\n\t"
      "movl 0x5a90d4, %%ecx\n\t"
      "pushl %%edi\n\t"
      "pushl %%ecx\n\t"
      "call *%[dget]\n\t"
      "movl %%eax, %%esi\n\t"
      "movl 0x8(%%esi), %%edx\n\t"
      "pushl %%edx\n\t"
      "pushl $0x616e7421\n\t"
      "call *%[tag]\n\t"
      "movl %%eax, %%ecx\n\t"
      "movb 0x5(%%esi), %%al\n\t"
      "addl $0x10, %%esp\n\t"
      "testb %%al, %%al\n\t"
      "jne .LFUN_00131790_4\n\t"
      "incw 0x6(%%esi)\n\t"
      "cmpl $-1, 0xc(%%esi)\n\t"
      "movw 0x6(%%esi), %%ax\n\t"
      "je .LFUN_00131790_4\n\t"
      "cmpw $5, %%ax\n\t"
      "jge .LFUN_00131790_4\n\t"
      "flds 0x8(%%ebp)\n\t"
      "fcomps 0x253d48\n\t"
      "fnstsw %%ax\n\t"
      "testb $0x41, %%ah\n\t"
      "jne .LFUN_00131790_2\n\t"
      "movl $0x3d888889, -0x4(%%ebp)\n\t"
      "jmp .LFUN_00131790_3\n\t"
      ".LFUN_00131790_2:\n\t"
      "movl 0x8(%%ebp), %%eax\n\t"
      "movl %%eax, -0x4(%%ebp)\n\t"
      ".LFUN_00131790_3:\n\t"
      "movl -0x4(%%ebp), %%edx\n\t"
      "pushl %%edx\n\t"
      "pushl %%ecx\n\t"
      "pushl %%esi\n\t"
      "call *%[c1313f0]\n\t"
      "addl $0xc, %%esp\n\t"
      ".LFUN_00131790_4:\n\t"
      "movl 0x5a90d4, %%eax\n\t"
      "pushl %%edi\n\t"
      "pushl %%eax\n\t"
      "call *%[c1198f0]\n\t"
      "movl %%eax, %%edi\n\t"
      "addl $8, %%esp\n\t"
      "cmpl $-1, %%edi\n\t"
      "jne .LFUN_00131790_1\n\t"
      "popl %%esi\n\t"
      ".LFUN_00131790_5:\n\t"
      "popl %%edi\n\t"
      "movl %%ebp, %%esp\n\t"
      "popl %%ebp\n\t"
      "ret\n\t"
      :
      : [c1198f0] "m"(b131790_c1198f0), [dget] "m"(b131790_dget), [tag] "m"(b131790_tag), [c1313f0] "m"(b131790_c1313f0)
      : "memory");
}
#else
#error "FUN_00131790: clang naked draft required"
#endif


/* FUN_00131840 (0x131840) — readable C lift. */
void *FUN_00131840(void *base, short *dims, short x, short y)
{
  extern char DAT_0029aa08[];
  extern char DAT_0029aa24[];
  extern char DAT_0029aa38[];
  extern char DAT_0029a9e8[];
  int idx;

  if (base == 0 || dims == 0) {
    display_assert(DAT_0029aa24, DAT_0029aa38, 0x60, 1);
    system_exit(-1);
  }
  if (x < 0 || x >= dims[6]) {
    display_assert(DAT_0029aa08, DAT_0029aa38, 0x61, 1);
    system_exit(-1);
  }
  if (y < 0 || y >= dims[7]) {
    display_assert(DAT_0029a9e8, DAT_0029aa38, 0x62, 1);
    system_exit(-1);
  }
  idx = (int)dims[7] * (int)x + (int)y;
  return (char *)base + idx * 24 + 0x1c;
}
/* telnet_console_print (0x1318f0) — readable C lift (grid cell ptr). */
void *telnet_console_print(void *base, short *dims, short x, short y)
{
  extern char DAT_0029aa24[];
  extern char DAT_0029aa38[];
  extern char DAT_0029aa60[];
  extern char DAT_0029aa80[];
  int idx;

  if (base == 0 || dims == 0) {
    display_assert(DAT_0029aa24, DAT_0029aa38, 0x6d, 1);
    system_exit(-1);
  }
  if (x < 0 || (int)x >= (int)dims[6] - 1) {
    display_assert(DAT_0029aa80, DAT_0029aa38, 0x6e, 1);
    system_exit(-1);
  }
  if (y < 0 || (int)y >= (int)dims[7] - 1) {
    display_assert(DAT_0029aa60, DAT_0029aa38, 0x6f, 1);
    system_exit(-1);
  }
  idx = ((int)dims[7] - 1) * (int)x + (int)y;
  return (char *)base + idx * 2 + 0x1534;
}
/* FUN_001319b0 (0x1319b0) — readable C lift. */
void FUN_001319b0(void)
{
  void *p = game_state_data_new(0x29aac0, 2, 0x16bc);
  *(void **)0x5a90d0 = p;
  if (p == NULL)
    error(p, 0x29aaa0);
}

/* FUN_001319e0 (0x1319e0) — readable C lift. */
void FUN_001319e0(void)
{
  data_delete_all(*(data_t **)0x5a90d0);
}

/* FUN_001319f0 (0x1319f0) — readable C lift. */
void FUN_001319f0(void)
{
  data_make_invalid(*(data_t **)0x5a90d0);
}

/* FUN_00131a00 (0x131a00) — readable C lift. */
void FUN_00131a00(void)
{
  if (*(int *)0x5a90d0 != 0) {
    *(int *)0x5a90d0 = 0;
  }
}

/* FUN_00131a20 (0x131a20) — XBE naked draft (batch 126). */
#if defined(__clang__)
static void (*const b131a20_c1318f0)(void) = telnet_console_print;

__attribute__((naked, noinline))
void FUN_00131a20(void)
{
  __asm__ volatile(
      "pushl %%ebp\n\t"
      "movl %%esp, %%ebp\n\t"
      "subl $0x10, %%esp\n\t"
      "movl 0x10(%%ebp), %%eax\n\t"
      "movswl %%ax, %%edx\n\t"
      "movl %%eax, 0x10(%%ebp)\n\t"
      "movswl 0x18(%%ebp), %%eax\n\t"
      "leal (%%eax,%%edx,1), %%ecx\n\t"
      "cmpl %%ecx, %%edx\n\t"
      "movl %%edx, -0x8(%%ebp)\n\t"
      "movl %%ecx, -0x10(%%ebp)\n\t"
      "jge .LFUN_00131a20_12\n\t"
      "pushl %%ebx\n\t"
      "movl 0x14(%%ebp), %%ebx\n\t"
      "movswl %%bx, %%ecx\n\t"
      "pushl %%esi\n\t"
      "addl %%eax, %%ecx\n\t"
      "movl %%edx, %%esi\n\t"
      "pushl %%edi\n\t"
      "movl %%ecx, -0xc(%%ebp)\n\t"
      "movl %%esi, -0x4(%%ebp)\n\t"
      "jmp .LFUN_00131a20_2\n\t"
      ".LFUN_00131a20_1:\n\t"
      "movl -0x4(%%ebp), %%esi\n\t"
      "movl 0x14(%%ebp), %%ebx\n\t"
      "nop\n\t"
      ".LFUN_00131a20_2:\n\t"
      "movswl %%bx, %%edi\n\t"
      "cmpl %%ecx, %%edi\n\t"
      "jge .LFUN_00131a20_11\n\t"
      "jmp .LFUN_00131a20_3\n\t"
      "leal (%%ecx), %%ecx\n\t"
      ".LFUN_00131a20_3:\n\t"
      "cmpw $0, 0x10(%%ebp)\n\t"
      "jl .LFUN_00131a20_10\n\t"
      "testw %%bx, %%bx\n\t"
      "jl .LFUN_00131a20_10\n\t"
      "movl 0x8(%%ebp), %%eax\n\t"
      "movswl 0xc(%%eax), %%ecx\n\t"
      "decl %%ecx\n\t"
      "cmpl %%ecx, %%esi\n\t"
      "jge .LFUN_00131a20_10\n\t"
      "movswl 0xe(%%eax), %%eax\n\t"
      "decl %%eax\n\t"
      "cmpl %%eax, %%edi\n\t"
      "jge .LFUN_00131a20_10\n\t"
      "movw 0x1c(%%ebp), %%cx\n\t"
      "cmpw $4, %%cx\n\t"
      "je .LFUN_00131a20_4\n\t"
      "cmpw $5, %%cx\n\t"
      "je .LFUN_00131a20_4\n\t"
      "movswl 0x18(%%ebp), %%eax\n\t"
      "subl %%esi, %%eax\n\t"
      "leal -0x1(%%eax,%%edx,1), %%esi\n\t"
      "jmp .LFUN_00131a20_5\n\t"
      ".LFUN_00131a20_4:\n\t"
      "subl %%edx, %%esi\n\t"
      ".LFUN_00131a20_5:\n\t"
      "cmpw $4, %%cx\n\t"
      "je .LFUN_00131a20_6\n\t"
      "cmpw $2, %%cx\n\t"
      "je .LFUN_00131a20_6\n\t"
      "movswl 0x18(%%ebp), %%eax\n\t"
      "movl %%eax, %%ecx\n\t"
      "movswl 0x14(%%ebp), %%eax\n\t"
      "subl %%edi, %%ecx\n\t"
      "leal -0x1(%%ecx,%%eax,1), %%edi\n\t"
      "jmp .LFUN_00131a20_7\n\t"
      ".LFUN_00131a20_6:\n\t"
      "movswl 0x14(%%ebp), %%eax\n\t"
      "subl %%eax, %%edi\n\t"
      ".LFUN_00131a20_7:\n\t"
      "movl 0x10(%%ebp), %%edx\n\t"
      "movl 0x8(%%ebp), %%eax\n\t"
      "movl 0xc(%%ebp), %%ecx\n\t"
      "pushl %%ebx\n\t"
      "pushl %%edx\n\t"
      "pushl %%eax\n\t"
      "pushl %%ecx\n\t"
      "call *%[c1318f0]\n\t"
      "addl $0x10, %%esp\n\t"
      "cmpw %%di, %%si\n\t"
      "jne .LFUN_00131a20_8\n\t"
      "movw 0x1c(%%ebp), %%dx\n\t"
      "movw %%dx, (%%eax)\n\t"
      "jmp .LFUN_00131a20_9\n\t"
      ".LFUN_00131a20_8:\n\t"
      "xorl %%ecx, %%ecx\n\t"
      "cmpw %%di, %%si\n\t"
      "setle %%cl\n\t"
      "movw %%cx, (%%eax)\n\t"
      ".LFUN_00131a20_9:\n\t"
      "movl -0x8(%%ebp), %%edx\n\t"
      "movl -0x4(%%ebp), %%esi\n\t"
      ".LFUN_00131a20_10:\n\t"
      "movl -0xc(%%ebp), %%ecx\n\t"
      "incl %%ebx\n\t"
      "movswl %%bx, %%edi\n\t"
      "cmpl %%ecx, %%edi\n\t"
      "jl .LFUN_00131a20_3\n\t"
      ".LFUN_00131a20_11:\n\t"
      "movl 0x10(%%ebp), %%eax\n\t"
      "movl -0x10(%%ebp), %%esi\n\t"
      "incl %%eax\n\t"
      "movl %%eax, 0x10(%%ebp)\n\t"
      "movswl %%ax, %%eax\n\t"
      "cmpl %%esi, %%eax\n\t"
      "movl %%eax, -0x4(%%ebp)\n\t"
      "jl .LFUN_00131a20_1\n\t"
      "popl %%edi\n\t"
      "popl %%esi\n\t"
      "popl %%ebx\n\t"
      ".LFUN_00131a20_12:\n\t"
      "movl %%ebp, %%esp\n\t"
      "popl %%ebp\n\t"
      "ret\n\t"
      :
      : [c1318f0] "m"(b131a20_c1318f0)
      : "memory");
}
#else
#error "FUN_00131a20: clang naked draft required"
#endif


/* FUN_00131b40 (0x131b40) — readable C lift. */
void FUN_00131b40(int handle)
{
  datum_delete(*(data_t **)0x5a90d0, handle);
}

/* FUN_00131b60 (0x131b60) — XBE naked draft (batch 111). */
#if defined(__clang__)
static void *(*const b131b60_elem)(void *, int, int) = tag_block_get_element;
static short (*const b131b60_markers)(int, void *, void *, int) = object_get_markers_by_string_id;
static void (*const b131b60_c18f180)(void *location_out, void *point) = scenario_location_from_point;
static void (*const b131b60_ftol)(void) = FUN_001d9068;
static void (*const b131b60_c131840)(void) = FUN_00131840;

__attribute__((naked, noinline))
void FUN_00131b60(void)
{
  __asm__ volatile(
      "pushl %%ebp\n\t"
      "movl %%esp, %%ebp\n\t"
      "subl $0x84, %%esp\n\t"
      "pushl %%ebx\n\t"
      "movl 0xc(%%ebp), %%ebx\n\t"
      "movl 0x54(%%ebx), %%eax\n\t"
      "pushl %%esi\n\t"
      "pushl %%edi\n\t"
      "leal 0x54(%%ebx), %%edi\n\t"
      "xorl %%esi, %%esi\n\t"
      "cmpl %%esi, %%eax\n\t"
      "movl %%esi, -0x4(%%ebp)\n\t"
      "jle .LFUN_00131b60_2\n\t"
      "movl %%edi, %%edi\n\t"
      ".LFUN_00131b60_1:\n\t"
      "pushl $0x34\n\t"
      "pushl %%esi\n\t"
      "pushl %%edi\n\t"
      "call *%[elem]\n\t"
      "movl 0x8(%%ebp), %%edx\n\t"
      "pushl $1\n\t"
      "leal -0x84(%%ebp), %%ecx\n\t"
      "pushl %%ecx\n\t"
      "addl $0x14, %%eax\n\t"
      "pushl %%eax\n\t"
      "movl 0x8(%%edx), %%eax\n\t"
      "pushl %%eax\n\t"
      "call *%[markers]\n\t"
      "movl 0x14(%%ebp), %%edx\n\t"
      "leal (%%esi,%%esi,2), %%ecx\n\t"
      "leal (%%edx,%%ecx,4), %%eax\n\t"
      "movl -0x24(%%ebp), %%ecx\n\t"
      "movl -0x20(%%ebp), %%edx\n\t"
      "movl %%ecx, (%%eax)\n\t"
      "movl -0x1c(%%ebp), %%ecx\n\t"
      "movl %%edx, 0x4(%%eax)\n\t"
      "movl %%ecx, 0x8(%%eax)\n\t"
      "movl -0x4(%%ebp), %%eax\n\t"
      "addl $0x1c, %%esp\n\t"
      "incl %%eax\n\t"
      "movswl %%ax, %%esi\n\t"
      "movl %%eax, -0x4(%%ebp)\n\t"
      "cmpl (%%edi), %%esi\n\t"
      "jl .LFUN_00131b60_1\n\t"
      ".LFUN_00131b60_2:\n\t"
      "movl 0x14(%%ebp), %%edi\n\t"
      "movl 0x10(%%ebp), %%edx\n\t"
      "pushl %%edi\n\t"
      "pushl %%edx\n\t"
      "call *%[c18f180]\n\t"
      "movl 0x8(%%ebp), %%eax\n\t"
      "movb 0x2(%%eax), %%cl\n\t"
      "addl $8, %%esp\n\t"
      "testb %%cl, %%cl\n\t"
      "jne .LFUN_00131b60_17\n\t"
      "xorl %%esi, %%esi\n\t"
      "xorl %%eax, %%eax\n\t"
      "cmpw %%si, 0xe(%%ebx)\n\t"
      "jle .LFUN_00131b60_4\n\t"
      ".LFUN_00131b60_3:\n\t"
      "movl 0x20(%%ebp), %%edx\n\t"
      "movswl %%ax, %%ecx\n\t"
      "incl %%eax\n\t"
      "movw $0xffff, (%%edx,%%ecx,2)\n\t"
      "cmpw 0xe(%%ebx), %%ax\n\t"
      "jl .LFUN_00131b60_3\n\t"
      ".LFUN_00131b60_4:\n\t"
      "movl 0x54(%%ebx), %%ecx\n\t"
      "cmpl %%esi, %%ecx\n\t"
      "leal 0x54(%%ebx), %%eax\n\t"
      "movl %%esi, -0x4(%%ebp)\n\t"
      "jle .LFUN_00131b60_10\n\t"
      "leal (%%esp), %%esp\n\t"
      ".LFUN_00131b60_5:\n\t"
      "cmpw 0xe(%%ebx), %%si\n\t"
      "jge .LFUN_00131b60_10\n\t"
      "movswl -0x4(%%ebp), %%edi\n\t"
      "pushl $0x34\n\t"
      "pushl %%edi\n\t"
      "pushl %%eax\n\t"
      "call *%[elem]\n\t"
      "movw (%%eax), %%ax\n\t"
      "addl $0xc, %%esp\n\t"
      "testw %%ax, %%ax\n\t"
      "jge .LFUN_00131b60_6\n\t"
      "xorl %%ecx, %%ecx\n\t"
      "jmp .LFUN_00131b60_7\n\t"
      ".LFUN_00131b60_6:\n\t"
      "movswl 0xe(%%ebx), %%ecx\n\t"
      "movswl %%si, %%edx\n\t"
      "movswl %%ax, %%eax\n\t"
      "subl %%edx, %%ecx\n\t"
      "cmpl %%ecx, %%eax\n\t"
      "jg .LFUN_00131b60_7\n\t"
      "movl %%eax, %%ecx\n\t"
      ".LFUN_00131b60_7:\n\t"
      "movl 0x1c(%%ebp), %%eax\n\t"
      "movl -0x4(%%ebp), %%ebx\n\t"
      "andl $0xfffffffe, %%ecx\n\t"
      "movswl %%si, %%edx\n\t"
      "movw %%si, (%%eax,%%edi,2)\n\t"
      "movl 0x20(%%ebp), %%eax\n\t"
      "addl %%esi, %%ecx\n\t"
      "cmpw %%cx, %%si\n\t"
      "movl %%edx, -0xc(%%ebp)\n\t"
      "movw %%bx, (%%eax,%%edx,2)\n\t"
      "jg .LFUN_00131b60_9\n\t"
      "fildl -0xc(%%ebp)\n\t"
      "movswl %%cx, %%eax\n\t"
      "subl %%esi, %%ecx\n\t"
      "movl %%eax, -0xc(%%ebp)\n\t"
      "leal (%%edi,%%edi,2), %%eax\n\t"
      "fsts -0x8(%%ebp)\n\t"
      "movl 0x14(%%ebp), %%edi\n\t"
      "fisubrs -0xc(%%ebp)\n\t"
      "incl %%ecx\n\t"
      "movl %%edx, -0x4(%%ebp)\n\t"
      "movzwl %%cx, %%ecx\n\t"
      "leal (%%edi,%%eax,4), %%eax\n\t"
      "movl 0x18(%%ebp), %%edi\n\t"
      "leal (%%edx,%%edx,2), %%edx\n\t"
      "leal 0x8(%%edi,%%edx,4), %%edx\n\t"
      "addl %%ecx, %%esi\n\t"
      ".LFUN_00131b60_8:\n\t"
      "fildl -0x4(%%ebp)\n\t"
      "movl -0x4(%%ebp), %%edi\n\t"
      "incl %%edi\n\t"
      "addl $0xc, %%edx\n\t"
      "decl %%ecx\n\t"
      "fsubs -0x8(%%ebp)\n\t"
      "movl %%edi, -0x4(%%ebp)\n\t"
      ".byte 0xd8, 0xf1\n\t"
      "flds 0x2533c8\n\t"
      ".byte 0xd8, 0xe1\n\t"
      "fld %%st(0)\n\t"
      "fmuls (%%eax)\n\t"
      "fld %%st(2)\n\t"
      "fmuls 0xc(%%eax)\n\t"
      ".byte 0xde, 0xc1\n\t"
      "fstps -0x14(%%edx)\n\t"
      "fld %%st(0)\n\t"
      "fmuls 0x4(%%eax)\n\t"
      "fld %%st(2)\n\t"
      "fmuls 0x10(%%eax)\n\t"
      ".byte 0xde, 0xc1\n\t"
      "fstps -0x10(%%edx)\n\t"
      "fmuls 0x8(%%eax)\n\t"
      "fxch %%st(1)\n\t"
      "fmuls 0x14(%%eax)\n\t"
      ".byte 0xde, 0xc1\n\t"
      "fstps -0xc(%%edx)\n\t"
      "jne .LFUN_00131b60_8\n\t"
      "fstp %%st(0)\n\t"
      ".LFUN_00131b60_9:\n\t"
      "movl 0x14(%%ebp), %%edi\n\t"
      "decl %%esi\n\t"
      "incl %%ebx\n\t"
      "movswl %%bx, %%ecx\n\t"
      "movl %%ebx, -0x4(%%ebp)\n\t"
      "movl 0xc(%%ebp), %%ebx\n\t"
      "movl 0x54(%%ebx), %%edx\n\t"
      "cmpl %%edx, %%ecx\n\t"
      "leal 0x54(%%ebx), %%eax\n\t"
      "jl .LFUN_00131b60_5\n\t"
      ".LFUN_00131b60_10:\n\t"
      "movl 0x8(%%ebp), %%eax\n\t"
      "flds (%%edi)\n\t"
      "fsubs 0x10(%%eax)\n\t"
      "leal 0x10(%%eax), %%esi\n\t"
      "movl %%esi, -0x8(%%ebp)\n\t"
      "fstps -0x18(%%ebp)\n\t"
      "flds 0x4(%%edi)\n\t"
      "fsubs 0x14(%%eax)\n\t"
      "fstps -0x14(%%ebp)\n\t"
      "flds 0x8(%%edi)\n\t"
      "fsubs 0x18(%%eax)\n\t"
      "fstps -0x10(%%ebp)\n\t"
      "flds -0x18(%%ebp)\n\t"
      "call *%[ftol]\n\t"
      "cdq\n\t"
      "xorl %%edx, %%eax\n\t"
      "subl %%edx, %%eax\n\t"
      "movl %%eax, 0xc(%%ebp)\n\t"
      "fildl 0xc(%%ebp)\n\t"
      "fcomps 0x2533c8\n\t"
      "fnstsw %%ax\n\t"
      "testb $0x41, %%ah\n\t"
      "je .LFUN_00131b60_11\n\t"
      "flds -0x14(%%ebp)\n\t"
      "call *%[ftol]\n\t"
      "cdq\n\t"
      "xorl %%edx, %%eax\n\t"
      "subl %%edx, %%eax\n\t"
      "movl %%eax, 0xc(%%ebp)\n\t"
      "fildl 0xc(%%ebp)\n\t"
      "fcomps 0x2533c8\n\t"
      "fnstsw %%ax\n\t"
      "testb $0x41, %%ah\n\t"
      "je .LFUN_00131b60_11\n\t"
      "flds -0x10(%%ebp)\n\t"
      "call *%[ftol]\n\t"
      "cdq\n\t"
      "xorl %%edx, %%eax\n\t"
      "subl %%edx, %%eax\n\t"
      "movl %%eax, 0xc(%%ebp)\n\t"
      "fildl 0xc(%%ebp)\n\t"
      "fcomps 0x2533c8\n\t"
      "fnstsw %%ax\n\t"
      "testb $0x41, %%ah\n\t"
      "jne .LFUN_00131b60_16\n\t"
      ".LFUN_00131b60_11:\n\t"
      "xorl %%edi, %%edi\n\t"
      "cmpw %%di, 0xc(%%ebx)\n\t"
      "jle .LFUN_00131b60_15\n\t"
      "movw 0xe(%%ebx), %%ax\n\t"
      "leal (%%ebx), %%ebx\n\t"
      ".LFUN_00131b60_12:\n\t"
      "xorl %%esi, %%esi\n\t"
      "testw %%ax, %%ax\n\t"
      "jle .LFUN_00131b60_14\n\t"
      ".LFUN_00131b60_13:\n\t"
      "movl 0x8(%%ebp), %%edx\n\t"
      "pushl %%esi\n\t"
      "pushl %%edi\n\t"
      "pushl %%ebx\n\t"
      "pushl %%edx\n\t"
      "call *%[c131840]\n\t"
      "flds -0x18(%%ebp)\n\t"
      "fadds (%%eax)\n\t"
      "addl $0x10, %%esp\n\t"
      "incl %%esi\n\t"
      "fstps (%%eax)\n\t"
      "flds -0x14(%%ebp)\n\t"
      "fadds 0x4(%%eax)\n\t"
      "fstps 0x4(%%eax)\n\t"
      "flds -0x10(%%ebp)\n\t"
      "fadds 0x8(%%eax)\n\t"
      "fstps 0x8(%%eax)\n\t"
      "movw 0xe(%%ebx), %%ax\n\t"
      "cmpw %%ax, %%si\n\t"
      "jl .LFUN_00131b60_13\n\t"
      ".LFUN_00131b60_14:\n\t"
      "incl %%edi\n\t"
      "cmpw 0xc(%%ebx), %%di\n\t"
      "jl .LFUN_00131b60_12\n\t"
      "movl -0x8(%%ebp), %%esi\n\t"
      ".LFUN_00131b60_15:\n\t"
      "movl 0x14(%%ebp), %%edi\n\t"
      ".LFUN_00131b60_16:\n\t"
      "movl (%%edi), %%eax\n\t"
      "movl %%eax, (%%esi)\n\t"
      "movl 0x4(%%edi), %%ecx\n\t"
      "movl %%ecx, 0x4(%%esi)\n\t"
      "movl 0x8(%%edi), %%edx\n\t"
      "movl %%edx, 0x8(%%esi)\n\t"
      ".LFUN_00131b60_17:\n\t"
      "popl %%edi\n\t"
      "popl %%esi\n\t"
      "popl %%ebx\n\t"
      "movl %%ebp, %%esp\n\t"
      "popl %%ebp\n\t"
      "ret\n\t"
      :
      : [elem] "m"(b131b60_elem), [markers] "m"(b131b60_markers), [c18f180] "m"(b131b60_c18f180), [ftol] "m"(b131b60_ftol), [c131840] "m"(b131b60_c131840)
      : "memory");
}
#else
#error "FUN_00131b60: clang naked draft required"
#endif


/* FUN_00131e00 (0x131e00) — XBE naked draft (batch 134). */
#if defined(__clang__)
static void *(*const b131e00_elem)(void *, int, int) = tag_block_get_element;
static void (*const b131e00_c131a20)(void) = FUN_00131a20;

__attribute__((naked, noinline))
void FUN_00131e00(void)
{
  __asm__ volatile(
      "pushl %%ebp\n\t"
      "movl %%esp, %%ebp\n\t"
      "pushl %%ecx\n\t"
      "pushl %%esi\n\t"
      "movl 0x8(%%ebp), %%esi\n\t"
      "pushl %%edi\n\t"
      "xorl %%edi, %%edi\n\t"
      "cmpw %%di, 0x8(%%esi)\n\t"
      "je .LFUN_00131e00_6\n\t"
      "cmpl %%edi, 0x54(%%esi)\n\t"
      "movl %%edi, -0x4(%%ebp)\n\t"
      "jle .LFUN_00131e00_6\n\t"
      "pushl %%ebx\n\t"
      "jmp .LFUN_00131e00_2\n\t"
      ".LFUN_00131e00_1:\n\t"
      "movl 0x8(%%ebp), %%esi\n\t"
      "jmp .LFUN_00131e00_2\n\t"
      "leal (%%esp), %%esp\n\t"
      ".LFUN_00131e00_2:\n\t"
      "cmpw 0xe(%%esi), %%di\n\t"
      "jge .LFUN_00131e00_5\n\t"
      "movswl -0x4(%%ebp), %%eax\n\t"
      "pushl $0x34\n\t"
      "pushl %%eax\n\t"
      "leal 0x54(%%esi), %%eax\n\t"
      "pushl %%eax\n\t"
      "call *%[elem]\n\t"
      "movw (%%eax), %%cx\n\t"
      "addl $0xc, %%esp\n\t"
      "testw %%cx, %%cx\n\t"
      "jge .LFUN_00131e00_3\n\t"
      "xorl %%eax, %%eax\n\t"
      "jmp .LFUN_00131e00_4\n\t"
      ".LFUN_00131e00_3:\n\t"
      "movswl 0xe(%%esi), %%eax\n\t"
      "movswl %%di, %%edx\n\t"
      "movswl %%cx, %%ecx\n\t"
      "subl %%edx, %%eax\n\t"
      "cmpl %%eax, %%ecx\n\t"
      "jg .LFUN_00131e00_4\n\t"
      "movl %%ecx, %%eax\n\t"
      ".LFUN_00131e00_4:\n\t"
      "movl 0x8(%%ebp), %%ecx\n\t"
      "andl $0xfffffffe, %%eax\n\t"
      "movl %%eax, %%ebx\n\t"
      "movl 0xc(%%ebp), %%eax\n\t"
      "xorl %%esi, %%esi\n\t"
      "movw %%bx, %%si\n\t"
      "sarw $1, %%si\n\t"
      "pushl $4\n\t"
      "pushl %%esi\n\t"
      "pushl %%edi\n\t"
      "pushl $0\n\t"
      "pushl %%eax\n\t"
      "pushl %%ecx\n\t"
      "call *%[c131a20]\n\t"
      "movl 0xc(%%ebp), %%edx\n\t"
      "pushl $5\n\t"
      "pushl %%esi\n\t"
      "addl %%edi, %%esi\n\t"
      "pushl %%esi\n\t"
      "movl 0x8(%%ebp), %%esi\n\t"
      "pushl $0\n\t"
      "pushl %%edx\n\t"
      "pushl %%esi\n\t"
      "call *%[c131a20]\n\t"
      "movl -0x4(%%ebp), %%eax\n\t"
      "movl 0x54(%%esi), %%edx\n\t"
      "addl $0x30, %%esp\n\t"
      "addl %%ebx, %%edi\n\t"
      "incl %%eax\n\t"
      "movswl %%ax, %%ecx\n\t"
      "cmpl %%edx, %%ecx\n\t"
      "movl %%eax, -0x4(%%ebp)\n\t"
      "leal 0x54(%%esi), %%eax\n\t"
      "jl .LFUN_00131e00_1\n\t"
      ".LFUN_00131e00_5:\n\t"
      "popl %%ebx\n\t"
      ".LFUN_00131e00_6:\n\t"
      "popl %%edi\n\t"
      "popl %%esi\n\t"
      "movl %%ebp, %%esp\n\t"
      "popl %%ebp\n\t"
      "ret\n\t"
      :
      : [elem] "m"(b131e00_elem), [c131a20] "m"(b131e00_c131a20)
      : "memory");
}
#else
#error "FUN_00131e00: clang naked draft required"
#endif


/* FUN_00131ed0 (0x131ed0) — XBE naked draft (batch 125). */
#if defined(__clang__)
static void (*const b131ed0_c131a20)(void) = FUN_00131a20;

__attribute__((naked, noinline))
void FUN_00131ed0(void)
{
  __asm__ volatile(
      "pushl %%ebp\n\t"
      "movl %%esp, %%ebp\n\t"
      "pushl %%edi\n\t"
      "movl 0x8(%%ebp), %%edi\n\t"
      "movw 0x4(%%edi), %%cx\n\t"
      "testw %%cx, %%cx\n\t"
      "je .LFUN_00131ed0_7\n\t"
      "cmpw $3, %%cx\n\t"
      "pushl %%ebx\n\t"
      "pushl %%esi\n\t"
      "je .LFUN_00131ed0_1\n\t"
      "cmpw $4, %%cx\n\t"
      "je .LFUN_00131ed0_1\n\t"
      "movw 0xe(%%edi), %%si\n\t"
      "sarw $1, %%si\n\t"
      "jmp .LFUN_00131ed0_2\n\t"
      ".LFUN_00131ed0_1:\n\t"
      "movw 0xe(%%edi), %%si\n\t"
      "decw %%si\n\t"
      ".LFUN_00131ed0_2:\n\t"
      "movswl 0x6(%%edi), %%edx\n\t"
      "movswl 0xc(%%edi), %%eax\n\t"
      "addl %%edx, %%eax\n\t"
      "movswl %%si, %%edx\n\t"
      "subl %%edx, %%eax\n\t"
      "decl %%eax\n\t"
      "xorl %%ebx, %%ebx\n\t"
      "testl %%eax, %%eax\n\t"
      "setl %%bl\n\t"
      "decl %%ebx\n\t"
      "andl %%eax, %%ebx\n\t"
      "cmpw $3, %%cx\n\t"
      "jne .LFUN_00131ed0_3\n\t"
      "movl 0xc(%%ebp), %%eax\n\t"
      "pushl $3\n\t"
      "pushl %%esi\n\t"
      "pushl $0\n\t"
      "pushl %%ebx\n\t"
      "pushl %%eax\n\t"
      "pushl %%edi\n\t"
      "call *%[c131a20]\n\t"
      "addl $0x18, %%esp\n\t"
      "popl %%esi\n\t"
      "popl %%ebx\n\t"
      "popl %%edi\n\t"
      "popl %%ebp\n\t"
      "ret\n\t"
      ".LFUN_00131ed0_3:\n\t"
      "cmpw $4, %%cx\n\t"
      "jne .LFUN_00131ed0_4\n\t"
      "movl 0xc(%%ebp), %%ecx\n\t"
      "pushl $2\n\t"
      "pushl %%esi\n\t"
      "pushl $0\n\t"
      "pushl %%ebx\n\t"
      "pushl %%ecx\n\t"
      "pushl %%edi\n\t"
      "call *%[c131a20]\n\t"
      "addl $0x18, %%esp\n\t"
      "popl %%esi\n\t"
      "popl %%ebx\n\t"
      "popl %%edi\n\t"
      "popl %%ebp\n\t"
      "ret\n\t"
      ".LFUN_00131ed0_4:\n\t"
      "cmpw $1, %%cx\n\t"
      "jne .LFUN_00131ed0_5\n\t"
      "movl 0xc(%%ebp), %%edx\n\t"
      "pushl $2\n\t"
      "pushl %%esi\n\t"
      "pushl $0\n\t"
      "pushl %%ebx\n\t"
      "pushl %%edx\n\t"
      "pushl %%edi\n\t"
      "call *%[c131a20]\n\t"
      "movl 0xc(%%ebp), %%eax\n\t"
      "pushl $3\n\t"
      "pushl %%esi\n\t"
      "pushl %%esi\n\t"
      "pushl %%ebx\n\t"
      "pushl %%eax\n\t"
      "pushl %%edi\n\t"
      "call *%[c131a20]\n\t"
      "addl $0x30, %%esp\n\t"
      "popl %%esi\n\t"
      "popl %%ebx\n\t"
      "popl %%edi\n\t"
      "popl %%ebp\n\t"
      "ret\n\t"
      ".LFUN_00131ed0_5:\n\t"
      "cmpw $2, %%cx\n\t"
      "jne .LFUN_00131ed0_6\n\t"
      "movl 0xc(%%ebp), %%ecx\n\t"
      "pushl $3\n\t"
      "pushl %%esi\n\t"
      "pushl $0\n\t"
      "pushl %%ebx\n\t"
      "pushl %%ecx\n\t"
      "pushl %%edi\n\t"
      "call *%[c131a20]\n\t"
      "movl 0xc(%%ebp), %%edx\n\t"
      "pushl $2\n\t"
      "pushl %%esi\n\t"
      "pushl %%esi\n\t"
      "pushl %%ebx\n\t"
      "pushl %%edx\n\t"
      "pushl %%edi\n\t"
      "call *%[c131a20]\n\t"
      "addl $0x30, %%esp\n\t"
      ".LFUN_00131ed0_6:\n\t"
      "popl %%esi\n\t"
      "popl %%ebx\n\t"
      ".LFUN_00131ed0_7:\n\t"
      "popl %%edi\n\t"
      "popl %%ebp\n\t"
      "ret\n\t"
      :
      : [c131a20] "m"(b131ed0_c131a20)
      : "memory");
}
#else
#error "FUN_00131ed0: clang naked draft required"
#endif


/* FUN_00131fc0 (0x131fc0) — XBE naked draft (batch 107). */
#if defined(__clang__)
static void *(*const b131fc0_get)(int, int) = object_get_and_verify_type;
static void (*const b131fc0_c131b60)(void) = FUN_00131b60;
static bool (*const b131fc0_c18f3e0)(void *location, void *position, int16_t *out_sky_index) = FUN_0018f3e0;
static void (*const b131fc0_c131840)(void) = FUN_00131840;
static void *(*const b131fc0_tag)(int, int) = tag_get;
static unsigned int *(*const b131fc0_lseed)(void) = random_math_get_local_seed_address;
static void (*const b131fc0_c10b380)(unsigned int *seed, float *out) = random_seed_get_direction3d;
static int (*const b131fc0_c154a50)(int flags, int physics_tag_data, int *collision_location, int object_handle, float *position, float *velocity, float *force, float *collision_normal_out, int16_t *surface_index_out, float radius, float delta_time) = FUN_00154a50;

__attribute__((naked, noinline))
void FUN_00131fc0(void)
{
  __asm__ volatile(
      "pushl %%ebp\n\t"
      "movl %%esp, %%ebp\n\t"
      "subl $0x300, %%esp\n\t"
      "pushl %%ebx\n\t"
      "pushl %%esi\n\t"
      "movl 0x8(%%ebp), %%esi\n\t"
      "movb 0x4(%%esi), %%bl\n\t"
      "movl 0x8(%%esi), %%ecx\n\t"
      "xorl %%eax, %%eax\n\t"
      "testb %%bl, %%bl\n\t"
      "sete %%al\n\t"
      "pushl %%edi\n\t"
      "movl $0xffffffff, %%ebx\n\t"
      "pushl %%ebx\n\t"
      "pushl %%ecx\n\t"
      "movl %%eax, -0x30(%%ebp)\n\t"
      "call *%[get]\n\t"
      "movl 0xc(%%ebp), %%edi\n\t"
      "leal -0x120(%%ebp), %%edx\n\t"
      "pushl %%edx\n\t"
      "leal -0x64(%%ebp), %%eax\n\t"
      "pushl %%eax\n\t"
      "leal -0x300(%%ebp), %%ecx\n\t"
      "pushl %%ecx\n\t"
      "leal -0xd0(%%ebp), %%edx\n\t"
      "pushl %%edx\n\t"
      "leal -0x48(%%ebp), %%eax\n\t"
      "pushl %%eax\n\t"
      "pushl %%edi\n\t"
      "pushl %%esi\n\t"
      "call *%[c131b60]\n\t"
      "movl 0x54(%%edi), %%eax\n\t"
      "leal -0x40(%%ebp), %%ecx\n\t"
      "pushl %%ecx\n\t"
      "leal (%%eax,%%eax,2), %%edx\n\t"
      "leal -0xdc(%%ebp,%%edx,4), %%eax\n\t"
      "pushl %%eax\n\t"
      "leal -0x48(%%ebp), %%ecx\n\t"
      "pushl %%ecx\n\t"
      "call *%[c18f3e0]\n\t"
      "movb %%al, 0xf(%%ebp)\n\t"
      "movb 0x2(%%esi), %%al\n\t"
      "addl $0x30, %%esp\n\t"
      "testb %%al, %%al\n\t"
      "jne .LFUN_00131fc0_22\n\t"
      "xorl %%edx, %%edx\n\t"
      "movw %%bx, -0x2c(%%ebp)\n\t"
      "movw %%dx, -0x2a(%%ebp)\n\t"
      "movw %%dx, -0x28(%%ebp)\n\t"
      "movw $1, -0x26(%%ebp)\n\t"
      "movw %%dx, -0x24(%%ebp)\n\t"
      "movw %%bx, -0x22(%%ebp)\n\t"
      "xorl %%eax, %%eax\n\t"
      "movl $3, %%ecx\n\t"
      ".LFUN_00131fc0_1:\n\t"
      "movswl -0x2c(%%ebp,%%eax,1), %%ebx\n\t"
      "movl %%ebx, -0x8(%%ebp)\n\t"
      "movswl -0x2a(%%ebp,%%eax,1), %%ebx\n\t"
      "fildl -0x8(%%ebp)\n\t"
      "movl %%ebx, -0x8(%%ebp)\n\t"
      "addl $4, %%eax\n\t"
      "decl %%ecx\n\t"
      "fmuls 0x10(%%edi)\n\t"
      "fildl -0x8(%%ebp)\n\t"
      "fmuls 0x14(%%edi)\n\t"
      "fld %%st(0)\n\t"
      ".byte 0xd8, 0xc9\n\t"
      "fld %%st(2)\n\t"
      ".byte 0xd8, 0xcb\n\t"
      ".byte 0xde, 0xc1\n\t"
      "fsqrt\n\t"
      "fstps -0x74(%%ebp,%%eax,1)\n\t"
      "fstp %%st(0)\n\t"
      "fstp %%st(0)\n\t"
      "jne .LFUN_00131fc0_1\n\t"
      "cmpw $0, 0xc(%%edi)\n\t"
      "movl %%edx, -0x10(%%ebp)\n\t"
      "jle .LFUN_00131fc0_22\n\t"
      "movl -0x30(%%ebp), %%ebx\n\t"
      "xorl %%eax, %%eax\n\t"
      "testw %%bx, %%bx\n\t"
      "setne %%al\n\t"
      "leal -0x1(%%eax,%%eax,1), %%eax\n\t"
      "movl %%eax, -0x4c(%%ebp)\n\t"
      ".LFUN_00131fc0_2:\n\t"
      "xorl %%eax, %%eax\n\t"
      "testw %%bx, %%bx\n\t"
      "je .LFUN_00131fc0_3\n\t"
      "movl %%eax, -0x4(%%ebp)\n\t"
      "jmp .LFUN_00131fc0_5\n\t"
      ".LFUN_00131fc0_3:\n\t"
      "movw 0xe(%%edi), %%ax\n\t"
      "decw %%ax\n\t"
      ".LFUN_00131fc0_4:\n\t"
      "movl %%eax, -0x4(%%ebp)\n\t"
      "leal (%%esp), %%esp\n\t"
      ".LFUN_00131fc0_5:\n\t"
      "xorl %%ecx, %%ecx\n\t"
      "testw %%bx, %%bx\n\t"
      "je .LFUN_00131fc0_6\n\t"
      "cmpw 0xe(%%edi), %%ax\n\t"
      "setl %%cl\n\t"
      "jmp .LFUN_00131fc0_7\n\t"
      ".LFUN_00131fc0_6:\n\t"
      "testw %%ax, %%ax\n\t"
      "setg %%cl\n\t"
      ".LFUN_00131fc0_7:\n\t"
      "testl %%ecx, %%ecx\n\t"
      "je .LFUN_00131fc0_21\n\t"
      "pushl %%eax\n\t"
      "pushl %%edx\n\t"
      "pushl %%edi\n\t"
      "pushl %%esi\n\t"
      "call *%[c131840]\n\t"
      "movl %%eax, %%ebx\n\t"
      "movb 0xf(%%ebp), %%al\n\t"
      "addl $0x10, %%esp\n\t"
      "testb %%al, %%al\n\t"
      "movl $0, -0x8(%%ebp)\n\t"
      "movl $1, %%esi\n\t"
      "jne .LFUN_00131fc0_8\n\t"
      "movl 0x34(%%edi), %%ecx\n\t"
      "pushl %%ecx\n\t"
      "pushl $0x70706879\n\t"
      "call *%[tag]\n\t"
      "flds 0x24(%%eax)\n\t"
      "fmuls 0x38(%%edi)\n\t"
      "fmuls 0x29aacc\n\t"
      "jmp .LFUN_00131fc0_9\n\t"
      ".LFUN_00131fc0_8:\n\t"
      "movl 0x34(%%edi), %%edx\n\t"
      "pushl %%edx\n\t"
      "pushl $0x70706879\n\t"
      "call *%[tag]\n\t"
      "flds 0x28(%%eax)\n\t"
      "fmuls 0x38(%%edi)\n\t"
      "movl $3, %%esi\n\t"
      "fmuls 0x29aac8\n\t"
      ".LFUN_00131fc0_9:\n\t"
      "leal -0x3c(%%ebp), %%eax\n\t"
      "fstps -0xc(%%ebp)\n\t"
      "addl $8, %%esp\n\t"
      "pushl %%eax\n\t"
      "call *%[lseed]\n\t"
      "pushl %%eax\n\t"
      "call *%[c10b380]\n\t"
      "flds -0x3c(%%ebp)\n\t"
      "fmuls -0xc(%%ebp)\n\t"
      "movl %%ebx, %%ecx\n\t"
      "addl $8, %%esp\n\t"
      "fstps -0x3c(%%ebp)\n\t"
      "flds -0x38(%%ebp)\n\t"
      "fmuls -0xc(%%ebp)\n\t"
      "fstps -0x38(%%ebp)\n\t"
      "flds -0x34(%%ebp)\n\t"
      "fmuls -0xc(%%ebp)\n\t"
      "fstps -0x34(%%ebp)\n\t"
      "movl (%%ecx), %%edx\n\t"
      "movl %%edx, -0x20(%%ebp)\n\t"
      "movl 0x4(%%ecx), %%eax\n\t"
      "movl -0x48(%%ebp), %%edx\n\t"
      "movl %%eax, -0x1c(%%ebp)\n\t"
      "movl 0x8(%%ecx), %%ecx\n\t"
      "movl -0x44(%%ebp), %%eax\n\t"
      "movl %%ecx, -0x18(%%ebp)\n\t"
      "movl 0x10(%%ebp), %%ecx\n\t"
      "pushl %%ecx\n\t"
      "movl -0x40(%%ebp), %%ecx\n\t"
      "pushl $0x3ca3d70a\n\t"
      "pushl $0\n\t"
      "pushl $0\n\t"
      "movl %%edx, -0x64(%%ebp)\n\t"
      "movl %%eax, -0x60(%%ebp)\n\t"
      "leal -0x3c(%%ebp), %%edx\n\t"
      "pushl %%edx\n\t"
      "leal 0xc(%%ebx), %%eax\n\t"
      "pushl %%eax\n\t"
      "leal -0x20(%%ebp), %%eax\n\t"
      "pushl %%eax\n\t"
      "movl 0x34(%%edi), %%eax\n\t"
      "pushl %%ecx\n\t"
      "leal -0x64(%%ebp), %%edx\n\t"
      "pushl %%edx\n\t"
      "pushl %%eax\n\t"
      "pushl $0x70706879\n\t"
      "call *%[tag]\n\t"
      "addl $8, %%esp\n\t"
      "pushl %%eax\n\t"
      "pushl %%esi\n\t"
      "call *%[c154a50]\n\t"
      "addl $0x2c, %%esp\n\t"
      "cmpw $0, -0x10(%%ebp)\n\t"
      "jne .LFUN_00131fc0_10\n\t"
      "movswl -0x4(%%ebp), %%eax\n\t"
      "movw -0x120(%%ebp,%%eax,2), %%ax\n\t"
      "cmpw $0xffff, %%ax\n\t"
      "je .LFUN_00131fc0_10\n\t"
      "movswl %%ax, %%eax\n\t"
      "leal (%%eax,%%eax,2), %%ecx\n\t"
      "leal -0xd0(%%ebp,%%ecx,4), %%edx\n\t"
      "movl (%%edx), %%eax\n\t"
      "movl 0x4(%%edx), %%ecx\n\t"
      "movl 0x8(%%edx), %%edx\n\t"
      "movl %%eax, -0x20(%%ebp)\n\t"
      "movl %%ecx, -0x1c(%%ebp)\n\t"
      "movl %%edx, -0x18(%%ebp)\n\t"
      "jmp .LFUN_00131fc0_20\n\t"
      ".LFUN_00131fc0_10:\n\t"
      "xorl %%esi, %%esi\n\t"
      "movl $3, -0xc(%%ebp)\n\t"
      "leal (%%ecx), %%ecx\n\t"
      ".LFUN_00131fc0_11:\n\t"
      "movw -0x2c(%%ebp,%%esi,1), %%ax\n\t"
      "addw -0x10(%%ebp), %%ax\n\t"
      "movw -0x2a(%%ebp,%%esi,1), %%cx\n\t"
      "addw -0x4(%%ebp), %%cx\n\t"
      "testw %%ax, %%ax\n\t"
      "jl .LFUN_00131fc0_14\n\t"
      "cmpw 0xc(%%edi), %%ax\n\t"
      "jge .LFUN_00131fc0_14\n\t"
      "testw %%cx, %%cx\n\t"
      "jl .LFUN_00131fc0_14\n\t"
      "cmpw 0xe(%%edi), %%cx\n\t"
      "jge .LFUN_00131fc0_14\n\t"
      "pushl %%ecx\n\t"
      "pushl %%eax\n\t"
      "movl 0x8(%%ebp), %%eax\n\t"
      "pushl %%edi\n\t"
      "pushl %%eax\n\t"
      "call *%[c131840]\n\t"
      "flds -0x20(%%ebp)\n\t"
      "movl %%eax, %%ecx\n\t"
      "fsubs (%%ecx)\n\t"
      "addl $0x10, %%esp\n\t"
      "flds -0x1c(%%ebp)\n\t"
      "fsubs 0x4(%%ecx)\n\t"
      "flds -0x18(%%ebp)\n\t"
      "fsubs 0x8(%%ecx)\n\t"
      "fsts -0x50(%%ebp)\n\t"
      "fmuls -0x50(%%ebp)\n\t"
      "fld %%st(1)\n\t"
      ".byte 0xd8, 0xca\n\t"
      ".byte 0xde, 0xc1\n\t"
      "fld %%st(2)\n\t"
      ".byte 0xd8, 0xcb\n\t"
      ".byte 0xde, 0xc1\n\t"
      "fsqrt\n\t"
      "fld %%st(0)\n\t"
      "fabs\n\t"
      "fcompl 0x2533d0\n\t"
      "fnstsw %%ax\n\t"
      "testb $5, %%ah\n\t"
      "jnp .LFUN_00131fc0_12\n\t"
      "fdivrs 0x2533c8\n\t"
      "fld %%st(0)\n\t"
      ".byte 0xde, 0xcb\n\t"
      "fld %%st(0)\n\t"
      ".byte 0xde, 0xca\n\t"
      "fmuls -0x50(%%ebp)\n\t"
      "fstps -0x50(%%ebp)\n\t"
      "jmp .LFUN_00131fc0_13\n\t"
      ".LFUN_00131fc0_12:\n\t"
      "fstp %%st(0)\n\t"
      ".LFUN_00131fc0_13:\n\t"
      "movl -0x8(%%ebp), %%edx\n\t"
      "fxch %%st(1)\n\t"
      "fmuls -0x70(%%ebp,%%esi,1)\n\t"
      "movswl %%dx, %%eax\n\t"
      "leal (%%eax,%%eax,2), %%eax\n\t"
      "shll $2, %%eax\n\t"
      "fadds (%%ecx)\n\t"
      "incl %%edx\n\t"
      "movl %%edx, -0x8(%%ebp)\n\t"
      "fstps -0x94(%%ebp,%%eax,1)\n\t"
      "fmuls -0x70(%%ebp,%%esi,1)\n\t"
      "fadds 0x4(%%ecx)\n\t"
      "fstps -0x90(%%ebp,%%eax,1)\n\t"
      "flds -0x50(%%ebp)\n\t"
      "fmuls -0x70(%%ebp,%%esi,1)\n\t"
      "fadds 0x8(%%ecx)\n\t"
      "fstps -0x8c(%%ebp,%%eax,1)\n\t"
      ".LFUN_00131fc0_14:\n\t"
      "movl -0xc(%%ebp), %%eax\n\t"
      "addl $4, %%esi\n\t"
      "decl %%eax\n\t"
      "movl %%eax, -0xc(%%ebp)\n\t"
      "jne .LFUN_00131fc0_11\n\t"
      "flds 0x2533c0\n\t"
      "movl -0x8(%%ebp), %%edx\n\t"
      "flds 0x2533c0\n\t"
      "movl $0, -0x14(%%ebp)\n\t"
      "flds 0x2533c0\n\t"
      "xorl %%ecx, %%ecx\n\t"
      "testw %%dx, %%dx\n\t"
      "flds -0x14(%%ebp)\n\t"
      "jle .LFUN_00131fc0_18\n\t"
      "jmp .LFUN_00131fc0_15\n\t"
      "leal (%%ecx), %%ecx\n\t"
      ".LFUN_00131fc0_15:\n\t"
      "cmpw $0, -0x10(%%ebp)\n\t"
      "je .LFUN_00131fc0_16\n\t"
      "testw %%cx, %%cx\n\t"
      "jne .LFUN_00131fc0_16\n\t"
      "flds 0x2533d8\n\t"
      "jmp .LFUN_00131fc0_17\n\t"
      ".LFUN_00131fc0_16:\n\t"
      "flds 0x2533c8\n\t"
      ".LFUN_00131fc0_17:\n\t"
      "fld %%st(0)\n\t"
      "movswl %%cx, %%eax\n\t"
      "leal (%%eax,%%eax,2), %%eax\n\t"
      "shll $2, %%eax\n\t"
      "incl %%ecx\n\t"
      "cmpw %%dx, %%cx\n\t"
      "fmuls -0x94(%%ebp,%%eax,1)\n\t"
      ".byte 0xde, 0xc3\n\t"
      "fld %%st(0)\n\t"
      "fmuls -0x90(%%ebp,%%eax,1)\n\t"
      ".byte 0xde, 0xc4\n\t"
      "fld %%st(0)\n\t"
      "fmuls -0x8c(%%ebp,%%eax,1)\n\t"
      ".byte 0xde, 0xc5\n\t"
      ".byte 0xde, 0xc1\n\t"
      "jl .LFUN_00131fc0_15\n\t"
      ".LFUN_00131fc0_18:\n\t"
      "cmpw $0, -0x10(%%ebp)\n\t"
      "jne .LFUN_00131fc0_19\n\t"
      "movswl -0x4(%%ebp), %%eax\n\t"
      "leal (%%eax,%%eax,2), %%eax\n\t"
      "shll $2, %%eax\n\t"
      "flds -0x300(%%ebp,%%eax,1)\n\t"
      "fmuls 0x2533d8\n\t"
      ".byte 0xde, 0xc2\n\t"
      "flds -0x2fc(%%ebp,%%eax,1)\n\t"
      "fmuls 0x2533d8\n\t"
      ".byte 0xde, 0xc3\n\t"
      "flds -0x2f8(%%ebp,%%eax,1)\n\t"
      "fmuls 0x2533d8\n\t"
      ".byte 0xde, 0xc4\n\t"
      "fadds 0x2533d8\n\t"
      ".LFUN_00131fc0_19:\n\t"
      "flds 0x2533c8\n\t"
      ".byte 0xd8, 0xf1\n\t"
      "fstps -0x14(%%ebp)\n\t"
      "fstp %%st(0)\n\t"
      "flds -0x14(%%ebp)\n\t"
      ".byte 0xd8, 0xc9\n\t"
      "fstps -0x20(%%ebp)\n\t"
      "fstp %%st(0)\n\t"
      "flds -0x14(%%ebp)\n\t"
      ".byte 0xd8, 0xc9\n\t"
      "fstps -0x1c(%%ebp)\n\t"
      "fstp %%st(0)\n\t"
      "flds -0x14(%%ebp)\n\t"
      ".byte 0xd8, 0xc9\n\t"
      "fstps -0x18(%%ebp)\n\t"
      "fstp %%st(0)\n\t"
      ".LFUN_00131fc0_20:\n\t"
      "flds 0x2533c8\n\t"
      "movl 0x8(%%ebp), %%esi\n\t"
      "fdivs 0x10(%%ebp)\n\t"
      "flds -0x20(%%ebp)\n\t"
      "fsubs (%%ebx)\n\t"
      ".byte 0xd8, 0xc9\n\t"
      "fstps 0xc(%%ebx)\n\t"
      "flds -0x1c(%%ebp)\n\t"
      "fsubs 0x4(%%ebx)\n\t"
      ".byte 0xd8, 0xc9\n\t"
      "fstps 0x10(%%ebx)\n\t"
      "flds -0x18(%%ebp)\n\t"
      "fsubs 0x8(%%ebx)\n\t"
      ".byte 0xd8, 0xc9\n\t"
      "fstps 0x14(%%ebx)\n\t"
      "movl -0x20(%%ebp), %%ecx\n\t"
      "movl %%ecx, (%%ebx)\n\t"
      "movl -0x1c(%%ebp), %%edx\n\t"
      "fstp %%st(0)\n\t"
      "movl -0x4c(%%ebp), %%ecx\n\t"
      "movl %%edx, 0x4(%%ebx)\n\t"
      "movl -0x18(%%ebp), %%eax\n\t"
      "movl -0x10(%%ebp), %%edx\n\t"
      "movl %%eax, 0x8(%%ebx)\n\t"
      "movl -0x4(%%ebp), %%eax\n\t"
      "movl -0x30(%%ebp), %%ebx\n\t"
      "addl %%ecx, %%eax\n\t"
      "jmp .LFUN_00131fc0_4\n\t"
      ".LFUN_00131fc0_21:\n\t"
      "incl %%edx\n\t"
      "cmpw 0xc(%%edi), %%dx\n\t"
      "movl %%edx, -0x10(%%ebp)\n\t"
      "jl .LFUN_00131fc0_2\n\t"
      ".LFUN_00131fc0_22:\n\t"
      "popl %%edi\n\t"
      "popl %%esi\n\t"
      "popl %%ebx\n\t"
      "movl %%ebp, %%esp\n\t"
      "popl %%ebp\n\t"
      "ret\n\t"
      :
      : [get] "m"(b131fc0_get), [c131b60] "m"(b131fc0_c131b60), [c18f3e0] "m"(b131fc0_c18f3e0), [c131840] "m"(b131fc0_c131840), [tag] "m"(b131fc0_tag), [lseed] "m"(b131fc0_lseed), [c10b380] "m"(b131fc0_c10b380), [c154a50] "m"(b131fc0_c154a50)
      : "memory");
}
#else
#error "FUN_00131fc0: clang naked draft required"
#endif


/* flag_render_proper (0x132460) — XBE naked draft (batch 104). */
#if defined(__clang__)
static void *(*const b132460_get)(int, int) = object_get_and_verify_type;
static int (*const b132460_c17c970)(int mode) = rasterizer_widget_submit;
static int (*const b132460_rzbuf)(int, int) = rasterizer_widget_set_zbuffer_enable;
static void *(*const b132460_tag)(int, int) = tag_get;
static int (*const b132460_rspr)(int) = rasterizer_widget_draw_sprite3d;
static void * (*const b132460_c17c980)(int handle) = rasterizer_widget_begin;
static void *(*const b132460_memset)(void *, int, unsigned int) = csmemset;
static void (*const b132460_c131840)(void) = FUN_00131840;
static void (*const b132460_c180d10)(short type, int count, int compressed_out, int compressed_size, void *uncompressed, int uncompressed_size) = FUN_00180d10;
static void (*const b132460_c1318f0)(void) = telnet_console_print;
static void (*const b132460_assert)(const char *, const char *, int, bool) = display_assert;
static void (*const b132460_exitfn)(int) = system_exit;
static void (*const b132460_c17c990)(int handle) = rasterizer_widget_set_texture;
static void (*const b132460_rend)(int) = rasterizer_widget_end;
static void (*const b132460_c17c960)(int param_1) = rasterizer_psuedo_dynamic_screen_quad_draw;
static void (*const b132460_c17d1a0)(int param_1) = FUN_0017d1a0;
static void (*const b132460_c17cbb0)(void *param_1, int param_2) = FUN_0017cbb0;
static char (*const b132460_c1909d0)(int16_t shader_type) = shader_type_is_transparent;
static void (*const b132460_c17cbd0)(int shader, int p2, int p3, int widget_handle, int p5, int p6, int zbuf_handle, float *position, int p9) = FUN_0017cbd0;
static void (*const b132460_c17cbc0)(int shader, int p2, int p3, int widget_handle, int p5, int p6, int zbuf_handle) = FUN_0017cbc0;
static void (*const b132460_c17cbe0)(void) = FUN_0017cbe0;
static void (*const b132460_c17cbf0)(void) = FUN_0017cbf0;
static void (*const b132460_c17c9a0)(int handle) = rasterizer_widget_set_tint_factor;
static void (*const b132460_rocc)(int) = rasterizer_widget_submit_occlusion_test;

__attribute__((naked, noinline))
void flag_render_proper(void)
{
  __asm__ volatile(
      "pushl %%ebp\n\t"
      "movl %%esp, %%ebp\n\t"
      "subl $0x160, %%esp\n\t"
      "pushl %%ebx\n\t"
      "pushl %%esi\n\t"
      "pushl %%edi\n\t"
      "movl 0x8(%%ebp), %%edi\n\t"
      "movl 0x8(%%edi), %%eax\n\t"
      "pushl $-1\n\t"
      "pushl %%eax\n\t"
      "call *%[get]\n\t"
      "movl 0xc(%%ebp), %%esi\n\t"
      "addl $8, %%esp\n\t"
      "cmpw $0, 0x68(%%eax)\n\t"
      "je .Lflag_render_proper_1\n\t"
      "movl 0x50(%%esi), %%ecx\n\t"
      "movl %%ecx, -0x18(%%ebp)\n\t"
      "jmp .Lflag_render_proper_2\n\t"
      ".Lflag_render_proper_1:\n\t"
      "movl 0x24(%%esi), %%edx\n\t"
      "movl %%edx, -0x18(%%ebp)\n\t"
      ".Lflag_render_proper_2:\n\t"
      "cmpl $-1, -0x18(%%ebp)\n\t"
      "jne .Lflag_render_proper_3\n\t"
      "movl 0x50(%%esi), %%eax\n\t"
      "movl %%eax, -0x18(%%ebp)\n\t"
      ".Lflag_render_proper_3:\n\t"
      "xorl %%eax, %%eax\n\t"
      "movw $0xb, 0x325652\n\t"
      "movw 0xe(%%esi), %%ax\n\t"
      "shlw $1, %%ax\n\t"
      "xorl %%ecx, %%ecx\n\t"
      "movw 0xc(%%esi), %%cx\n\t"
      "subl $2, %%eax\n\t"
      "decw %%cx\n\t"
      "imull %%ecx, %%eax\n\t"
      "movswl %%ax, %%edx\n\t"
      "pushl %%edx\n\t"
      "movl %%eax, -0x8(%%ebp)\n\t"
      "call *%[c17c970]\n\t"
      "movswl 0xe(%%esi), %%ecx\n\t"
      "movl %%eax, %%ebx\n\t"
      "movswl 0xc(%%esi), %%eax\n\t"
      "imull %%ecx, %%eax\n\t"
      "pushl %%eax\n\t"
      "pushl $5\n\t"
      "movl %%ebx, -0x14(%%ebp)\n\t"
      "call *%[rzbuf]\n\t"
      "addl $0xc, %%esp\n\t"
      "cmpl $-1, %%ebx\n\t"
      "movl %%eax, -0xc(%%ebp)\n\t"
      "je .Lflag_render_proper_34\n\t"
      "cmpl $-1, %%eax\n\t"
      "je .Lflag_render_proper_34\n\t"
      "movl 0x8(%%edi), %%edx\n\t"
      "pushl $-1\n\t"
      "pushl %%edx\n\t"
      "call *%[get]\n\t"
      "movl (%%eax), %%eax\n\t"
      "pushl %%eax\n\t"
      "pushl $0x6f626a65\n\t"
      "call *%[tag]\n\t"
      "movl -0xc(%%ebp), %%ecx\n\t"
      "pushl %%ecx\n\t"
      "call *%[rspr]\n\t"
      "pushl %%ebx\n\t"
      "movl %%eax, -0x30(%%ebp)\n\t"
      "call *%[c17c980]\n\t"
      "movswl 0xc(%%esi), %%edx\n\t"
      "decl %%edx\n\t"
      "movl %%edx, 0xc(%%ebp)\n\t"
      "movl %%eax, -0x4(%%ebp)\n\t"
      "movswl 0xe(%%esi), %%eax\n\t"
      "fildl 0xc(%%ebp)\n\t"
      "decl %%eax\n\t"
      "fdivrs 0x2533c8\n\t"
      "movl %%eax, 0xc(%%ebp)\n\t"
      "pushl $0x44\n\t"
      "leal -0x94(%%ebp), %%ecx\n\t"
      "pushl $0\n\t"
      "pushl %%ecx\n\t"
      "fstps -0x48(%%ebp)\n\t"
      "fildl 0xc(%%ebp)\n\t"
      "fdivrs 0x2533c8\n\t"
      "fstps -0x3c(%%ebp)\n\t"
      "call *%[memset]\n\t"
      "xorl %%eax, %%eax\n\t"
      "addl $0x24, %%esp\n\t"
      "cmpw %%ax, 0xc(%%esi)\n\t"
      "movl %%eax, -0x2c(%%ebp)\n\t"
      "movl %%eax, -0x34(%%ebp)\n\t"
      "jle .Lflag_render_proper_11\n\t"
      "jmp .Lflag_render_proper_4\n\t"
      "leal (%%esp), %%esp\n\t"
      ".Lflag_render_proper_4:\n\t"
      "cmpw $0, 0xe(%%esi)\n\t"
      "movl $0, -0x10(%%ebp)\n\t"
      "jle .Lflag_render_proper_10\n\t"
      "movswl %%ax, %%ebx\n\t"
      "movl %%ebx, -0x38(%%ebp)\n\t"
      "fildl -0x38(%%ebp)\n\t"
      "fmuls -0x48(%%ebp)\n\t"
      "fstps -0x44(%%ebp)\n\t"
      "jmp .Lflag_render_proper_6\n\t"
      ".Lflag_render_proper_5:\n\t"
      "movl -0x38(%%ebp), %%ebx\n\t"
      ".Lflag_render_proper_6:\n\t"
      "movl -0x10(%%ebp), %%edx\n\t"
      "pushl %%edx\n\t"
      "pushl %%eax\n\t"
      "pushl %%esi\n\t"
      "pushl %%edi\n\t"
      "call *%[c131840]\n\t"
      "movl %%eax, -0x40(%%ebp)\n\t"
      "movswl 0xc(%%esi), %%eax\n\t"
      "addl $0x10, %%esp\n\t"
      "decl %%eax\n\t"
      "cmpl %%eax, %%ebx\n\t"
      "jl .Lflag_render_proper_7\n\t"
      "decl %%ebx\n\t"
      ".Lflag_render_proper_7:\n\t"
      "movswl 0xe(%%esi), %%ecx\n\t"
      "movswl -0x10(%%ebp), %%eax\n\t"
      "decl %%ecx\n\t"
      "cmpl %%ecx, %%eax\n\t"
      "movl %%ebx, -0x1c(%%ebp)\n\t"
      "movl %%eax, -0x50(%%ebp)\n\t"
      "jl .Lflag_render_proper_8\n\t"
      "decl %%eax\n\t"
      ".Lflag_render_proper_8:\n\t"
      "movl %%eax, %%edx\n\t"
      "pushl %%edx\n\t"
      "movl %%eax, 0xc(%%ebp)\n\t"
      "movl -0x1c(%%ebp), %%eax\n\t"
      "pushl %%eax\n\t"
      "pushl %%esi\n\t"
      "pushl %%edi\n\t"
      "call *%[c131840]\n\t"
      "movl 0xc(%%ebp), %%ecx\n\t"
      "movl -0x1c(%%ebp), %%edx\n\t"
      "pushl %%ecx\n\t"
      "incl %%edx\n\t"
      "pushl %%edx\n\t"
      "pushl %%esi\n\t"
      "pushl %%edi\n\t"
      "movl %%eax, %%ebx\n\t"
      "call *%[c131840]\n\t"
      "movl -0x1c(%%ebp), %%ecx\n\t"
      "movl %%eax, -0x4c(%%ebp)\n\t"
      "movl 0xc(%%ebp), %%eax\n\t"
      "incl %%eax\n\t"
      "pushl %%eax\n\t"
      "pushl %%ecx\n\t"
      "pushl %%esi\n\t"
      "pushl %%edi\n\t"
      "call *%[c131840]\n\t"
      "movl -0x4c(%%ebp), %%ecx\n\t"
      "flds (%%ecx)\n\t"
      "addl $0x30, %%esp\n\t"
      "fsubs (%%ebx)\n\t"
      "flds 0x4(%%ecx)\n\t"
      "fsubs 0x4(%%ebx)\n\t"
      "flds 0x8(%%ecx)\n\t"
      "fsubs 0x8(%%ebx)\n\t"
      "flds (%%eax)\n\t"
      "fsubs (%%ebx)\n\t"
      "fstps -0x28(%%ebp)\n\t"
      "flds 0x4(%%eax)\n\t"
      "fsubs 0x4(%%ebx)\n\t"
      "fstps -0x24(%%ebp)\n\t"
      "flds 0x8(%%eax)\n\t"
      "fsubs 0x8(%%ebx)\n\t"
      "fld %%st(0)\n\t"
      ".byte 0xd8, 0xcb\n\t"
      "flds -0x24(%%ebp)\n\t"
      ".byte 0xd8, 0xcb\n\t"
      ".byte 0xde, 0xe9\n\t"
      "fstps -0x88(%%ebp)\n\t"
      "flds -0x28(%%ebp)\n\t"
      ".byte 0xd8, 0xca\n\t"
      "fxch %%st(1)\n\t"
      ".byte 0xd8, 0xcc\n\t"
      ".byte 0xde, 0xe9\n\t"
      "fstps -0x84(%%ebp)\n\t"
      "fstp %%st(0)\n\t"
      "flds -0x24(%%ebp)\n\t"
      ".byte 0xd8, 0xca\n\t"
      "flds -0x28(%%ebp)\n\t"
      ".byte 0xd8, 0xca\n\t"
      ".byte 0xde, 0xe9\n\t"
      "fstps -0x80(%%ebp)\n\t"
      "fstp %%st(0)\n\t"
      "fstp %%st(0)\n\t"
      "flds -0x80(%%ebp)\n\t"
      "fmuls -0x80(%%ebp)\n\t"
      "flds -0x84(%%ebp)\n\t"
      "fmuls -0x84(%%ebp)\n\t"
      ".byte 0xde, 0xc1\n\t"
      "flds -0x88(%%ebp)\n\t"
      "fmuls -0x88(%%ebp)\n\t"
      ".byte 0xde, 0xc1\n\t"
      "fsqrt\n\t"
      "fld %%st(0)\n\t"
      "fabs\n\t"
      "fcompl 0x2533d0\n\t"
      "fnstsw %%ax\n\t"
      "testb $5, %%ah\n\t"
      "jnp .Lflag_render_proper_9\n\t"
      "fdivrs 0x2533c8\n\t"
      "flds -0x88(%%ebp)\n\t"
      ".byte 0xd8, 0xc9\n\t"
      "fstps -0x88(%%ebp)\n\t"
      "flds -0x84(%%ebp)\n\t"
      ".byte 0xd8, 0xc9\n\t"
      "fstps -0x84(%%ebp)\n\t"
      "flds -0x80(%%ebp)\n\t"
      ".byte 0xd8, 0xc9\n\t"
      "fstps -0x80(%%ebp)\n\t"
      ".Lflag_render_proper_9:\n\t"
      "movl -0x40(%%ebp), %%eax\n\t"
      "fstp %%st(0)\n\t"
      "movl (%%eax), %%edx\n\t"
      "fildl -0x50(%%ebp)\n\t"
      "movl -0x34(%%ebp), %%ebx\n\t"
      "movl %%edx, -0x94(%%ebp)\n\t"
      "movl 0x4(%%eax), %%ecx\n\t"
      "fmuls -0x3c(%%ebp)\n\t"
      "movl %%ecx, -0x90(%%ebp)\n\t"
      "movl 0x8(%%eax), %%edx\n\t"
      "movl -0x44(%%ebp), %%eax\n\t"
      "fstps -0x60(%%ebp)\n\t"
      "movl %%edx, -0x8c(%%ebp)\n\t"
      "pushl $0x44\n\t"
      "leal -0x94(%%ebp), %%ecx\n\t"
      "pushl %%ecx\n\t"
      "movl -0x30(%%ebp), %%ecx\n\t"
      "movswl %%bx, %%edx\n\t"
      "shll $5, %%edx\n\t"
      "pushl $0x20\n\t"
      "addl %%ecx, %%edx\n\t"
      "pushl %%edx\n\t"
      "pushl $1\n\t"
      "pushl $4\n\t"
      "movl %%eax, -0x64(%%ebp)\n\t"
      "call *%[c180d10]\n\t"
      "movl -0x10(%%ebp), %%eax\n\t"
      "addl $0x18, %%esp\n\t"
      "incl %%eax\n\t"
      "incl %%ebx\n\t"
      "cmpw 0xe(%%esi), %%ax\n\t"
      "movl %%eax, -0x10(%%ebp)\n\t"
      "movl -0x2c(%%ebp), %%eax\n\t"
      "movl %%ebx, -0x34(%%ebp)\n\t"
      "jl .Lflag_render_proper_5\n\t"
      ".Lflag_render_proper_10:\n\t"
      "incl %%eax\n\t"
      "cmpw 0xc(%%esi), %%ax\n\t"
      "movl %%eax, -0x2c(%%ebp)\n\t"
      "jl .Lflag_render_proper_4\n\t"
      ".Lflag_render_proper_11:\n\t"
      "movswl 0xc(%%esi), %%eax\n\t"
      "xorl %%ebx, %%ebx\n\t"
      "decl %%eax\n\t"
      "testl %%eax, %%eax\n\t"
      "movl %%ebx, 0xc(%%ebp)\n\t"
      "jle .Lflag_render_proper_29\n\t"
      "leal (%%ebx), %%ebx\n\t"
      ".Lflag_render_proper_12:\n\t"
      "movswl 0xe(%%esi), %%ecx\n\t"
      "xorl %%edi, %%edi\n\t"
      "decl %%ecx\n\t"
      "testl %%ecx, %%ecx\n\t"
      "jle .Lflag_render_proper_28\n\t"
      "nop\n\t"
      ".Lflag_render_proper_13:\n\t"
      "movl 0x8(%%ebp), %%edx\n\t"
      "pushl %%edi\n\t"
      "pushl %%ebx\n\t"
      "pushl %%esi\n\t"
      "pushl %%edx\n\t"
      "call *%[c1318f0]\n\t"
      "movswl (%%eax), %%eax\n\t"
      "addl $0x10, %%esp\n\t"
      "cmpl $5, %%eax\n\t"
      "ja .Lflag_render_proper_26\n\t"
      "jmp *.Lflag_render_proper_jt(,%%eax,4)\n\t"
      ".Lflag_render_proper_14:\n\t"
      "movl 0xc(%%ebp), %%eax\n\t"
      "cmpw -0x8(%%ebp), %%ax\n\t"
      "jl .Lflag_render_proper_15\n\t"
      "pushl $1\n\t"
      "pushl $0x2e6\n\t"
      "pushl $0x29aa38\n\t"
      "pushl $0x29aad0\n\t"
      "call *%[assert]\n\t"
      "pushl $-1\n\t"
      "call *%[exitfn]\n\t"
      "movl 0xc(%%ebp), %%eax\n\t"
      "addl $0x14, %%esp\n\t"
      ".Lflag_render_proper_15:\n\t"
      "movl -0x4(%%ebp), %%edx\n\t"
      "movswl %%ax, %%ecx\n\t"
      "leal (%%ecx,%%ecx,2), %%ecx\n\t"
      "leal (%%edx,%%ecx,2), %%ecx\n\t"
      "xorl %%edx, %%edx\n\t"
      "movw 0xe(%%esi), %%dx\n\t"
      "imulw %%bx, %%dx\n\t"
      "movl %%ecx, 0xc(%%ebp)\n\t"
      "addl %%edi, %%edx\n\t"
      "movw %%dx, (%%ecx)\n\t"
      "xorl %%edx, %%edx\n\t"
      "movw 0xe(%%esi), %%dx\n\t"
      "leal 0x1(%%ebx), %%ecx\n\t"
      "imulw %%cx, %%dx\n\t"
      "movl 0xc(%%ebp), %%ecx\n\t"
      "addl %%edi, %%edx\n\t"
      "movw %%dx, 0x2(%%ecx)\n\t"
      "xorl %%edx, %%edx\n\t"
      "movw 0xe(%%esi), %%dx\n\t"
      "imulw %%bx, %%dx\n\t"
      "incl %%eax\n\t"
      "cmpw -0x8(%%ebp), %%ax\n\t"
      "movl %%eax, 0xc(%%ebp)\n\t"
      "leal 0x1(%%edx,%%edi,1), %%edx\n\t"
      "movw %%dx, 0x4(%%ecx)\n\t"
      "jl .Lflag_render_proper_16\n\t"
      "pushl $1\n\t"
      "pushl $0x2eb\n\t"
      "pushl $0x29aa38\n\t"
      "pushl $0x29aad0\n\t"
      "call *%[assert]\n\t"
      "pushl $-1\n\t"
      "call *%[exitfn]\n\t"
      "movl 0xc(%%ebp), %%eax\n\t"
      "addl $0x14, %%esp\n\t"
      ".Lflag_render_proper_16:\n\t"
      "movl -0x4(%%ebp), %%edx\n\t"
      "movswl %%ax, %%ecx\n\t"
      "leal (%%ecx,%%ecx,2), %%ecx\n\t"
      "leal (%%edx,%%ecx,2), %%ecx\n\t"
      "xorl %%edx, %%edx\n\t"
      "movw 0xe(%%esi), %%dx\n\t"
      "imulw %%bx, %%dx\n\t"
      "movl %%ecx, 0xc(%%ebp)\n\t"
      "leal 0x1(%%edx,%%edi,1), %%edx\n\t"
      "movw %%dx, (%%ecx)\n\t"
      "xorl %%edx, %%edx\n\t"
      "movw 0xe(%%esi), %%dx\n\t"
      "leal 0x1(%%ebx), %%ecx\n\t"
      "imulw %%cx, %%dx\n\t"
      "movl 0xc(%%ebp), %%ecx\n\t"
      "addl %%edi, %%edx\n\t"
      "movw %%dx, 0x2(%%ecx)\n\t"
      "xorl %%edx, %%edx\n\t"
      "movw 0xe(%%esi), %%dx\n\t"
      "leal 0x1(%%ebx), %%ecx\n\t"
      "imulw %%cx, %%dx\n\t"
      "incl %%eax\n\t"
      "leal 0x1(%%edx,%%edi,1), %%ecx\n\t"
      "movl 0xc(%%ebp), %%edx\n\t"
      "movw %%cx, 0x4(%%edx)\n\t"
      "movl %%eax, 0xc(%%ebp)\n\t"
      "jmp .Lflag_render_proper_27\n\t"
      ".Lflag_render_proper_17:\n\t"
      "movw 0xc(%%ebp), %%ax\n\t"
      "cmpw -0x8(%%ebp), %%ax\n\t"
      "jl .Lflag_render_proper_18\n\t"
      "pushl $1\n\t"
      "pushl $0x2f2\n\t"
      "pushl $0x29aa38\n\t"
      "pushl $0x29aad0\n\t"
      "call *%[assert]\n\t"
      "pushl $-1\n\t"
      "call *%[exitfn]\n\t"
      "addl $0x14, %%esp\n\t"
      ".Lflag_render_proper_18:\n\t"
      "movl 0xc(%%ebp), %%ecx\n\t"
      "movswl %%cx, %%eax\n\t"
      "leal (%%eax,%%eax,2), %%edx\n\t"
      "movl -0x4(%%ebp), %%eax\n\t"
      "leal (%%eax,%%edx,2), %%eax\n\t"
      "xorl %%edx, %%edx\n\t"
      "movw 0xe(%%esi), %%dx\n\t"
      "imulw %%bx, %%dx\n\t"
      "addl %%edi, %%edx\n\t"
      "movw %%dx, (%%eax)\n\t"
      "xorl %%edx, %%edx\n\t"
      "movw 0xe(%%esi), %%dx\n\t"
      "imulw %%bx, %%dx\n\t"
      "leal 0x1(%%edx,%%edi,1), %%edx\n\t"
      "movw %%dx, 0x2(%%eax)\n\t"
      "leal 0x1(%%ebx), %%edx\n\t"
      "imulw 0xe(%%esi), %%dx\n\t"
      "addl %%edi, %%edx\n\t"
      "incl %%ecx\n\t"
      "movw %%dx, 0x4(%%eax)\n\t"
      "movl %%ecx, 0xc(%%ebp)\n\t"
      "jmp .Lflag_render_proper_27\n\t"
      ".Lflag_render_proper_19:\n\t"
      "movw 0xc(%%ebp), %%ax\n\t"
      "cmpw -0x8(%%ebp), %%ax\n\t"
      "jl .Lflag_render_proper_20\n\t"
      "pushl $1\n\t"
      "pushl $0x2f9\n\t"
      "pushl $0x29aa38\n\t"
      "pushl $0x29aad0\n\t"
      "call *%[assert]\n\t"
      "pushl $-1\n\t"
      "call *%[exitfn]\n\t"
      "addl $0x14, %%esp\n\t"
      ".Lflag_render_proper_20:\n\t"
      "movl 0xc(%%ebp), %%ecx\n\t"
      "movswl %%cx, %%eax\n\t"
      "leal (%%eax,%%eax,2), %%edx\n\t"
      "movl -0x4(%%ebp), %%eax\n\t"
      "leal (%%eax,%%edx,2), %%eax\n\t"
      "xorl %%edx, %%edx\n\t"
      "movw 0xe(%%esi), %%dx\n\t"
      "imulw %%bx, %%dx\n\t"
      "addl %%edi, %%edx\n\t"
      "movw %%dx, (%%eax)\n\t"
      "xorl %%edx, %%edx\n\t"
      "movw 0xe(%%esi), %%dx\n\t"
      "imulw %%bx, %%dx\n\t"
      "leal 0x1(%%edx,%%edi,1), %%edx\n\t"
      "movw %%dx, 0x2(%%eax)\n\t"
      "leal 0x1(%%ebx), %%edx\n\t"
      "imulw 0xe(%%esi), %%dx\n\t"
      "incl %%ecx\n\t"
      "movl %%ecx, 0xc(%%ebp)\n\t"
      "leal 0x1(%%edx,%%edi,1), %%edx\n\t"
      "movw %%dx, 0x4(%%eax)\n\t"
      "jmp .Lflag_render_proper_27\n\t"
      ".Lflag_render_proper_21:\n\t"
      "movw 0xc(%%ebp), %%ax\n\t"
      "cmpw -0x8(%%ebp), %%ax\n\t"
      "jl .Lflag_render_proper_22\n\t"
      "pushl $1\n\t"
      "pushl $0x300\n\t"
      "pushl $0x29aa38\n\t"
      "pushl $0x29aad0\n\t"
      "call *%[assert]\n\t"
      "pushl $-1\n\t"
      "call *%[exitfn]\n\t"
      "addl $0x14, %%esp\n\t"
      ".Lflag_render_proper_22:\n\t"
      "movswl 0xc(%%ebp), %%eax\n\t"
      "movl -0x4(%%ebp), %%edx\n\t"
      "leal (%%eax,%%eax,2), %%ecx\n\t"
      "leal (%%edx,%%ecx,2), %%eax\n\t"
      "xorl %%ecx, %%ecx\n\t"
      "movw 0xe(%%esi), %%cx\n\t"
      "imulw %%bx, %%cx\n\t"
      "addl %%edi, %%ecx\n\t"
      "movw %%cx, (%%eax)\n\t"
      "jmp .Lflag_render_proper_25\n\t"
      ".Lflag_render_proper_23:\n\t"
      "movw 0xc(%%ebp), %%ax\n\t"
      "cmpw -0x8(%%ebp), %%ax\n\t"
      "jl .Lflag_render_proper_24\n\t"
      "pushl $1\n\t"
      "pushl $0x307\n\t"
      "pushl $0x29aa38\n\t"
      "pushl $0x29aad0\n\t"
      "call *%[assert]\n\t"
      "pushl $-1\n\t"
      "call *%[exitfn]\n\t"
      "addl $0x14, %%esp\n\t"
      ".Lflag_render_proper_24:\n\t"
      "movswl 0xc(%%ebp), %%eax\n\t"
      "movl -0x4(%%ebp), %%edx\n\t"
      "leal (%%eax,%%eax,2), %%ecx\n\t"
      "leal (%%edx,%%ecx,2), %%eax\n\t"
      "xorl %%ecx, %%ecx\n\t"
      "movw 0xe(%%esi), %%cx\n\t"
      "imulw %%bx, %%cx\n\t"
      "leal 0x1(%%ecx,%%edi,1), %%edx\n\t"
      "movw %%dx, (%%eax)\n\t"
      ".Lflag_render_proper_25:\n\t"
      "xorl %%edx, %%edx\n\t"
      "movw 0xe(%%esi), %%dx\n\t"
      "leal 0x1(%%ebx), %%ecx\n\t"
      "imulw %%cx, %%dx\n\t"
      "leal 0x1(%%edx,%%edi,1), %%edx\n\t"
      "movw %%dx, 0x2(%%eax)\n\t"
      "xorl %%edx, %%edx\n\t"
      "movw 0xe(%%esi), %%dx\n\t"
      "imulw %%cx, %%dx\n\t"
      "addl %%edi, %%edx\n\t"
      "movw %%dx, 0x4(%%eax)\n\t"
      "incl 0xc(%%ebp)\n\t"
      "jmp .Lflag_render_proper_27\n\t"
      ".Lflag_render_proper_26:\n\t"
      "pushl $1\n\t"
      "pushl $0x310\n\t"
      "pushl $0x29aa38\n\t"
      "pushl $0\n\t"
      "call *%[assert]\n\t"
      "pushl $-1\n\t"
      "call *%[exitfn]\n\t"
      "addl $0x14, %%esp\n\t"
      ".Lflag_render_proper_27:\n\t"
      "movswl 0xe(%%esi), %%eax\n\t"
      "incl %%edi\n\t"
      "movswl %%di, %%ecx\n\t"
      "decl %%eax\n\t"
      "cmpl %%eax, %%ecx\n\t"
      "jl .Lflag_render_proper_13\n\t"
      ".Lflag_render_proper_28:\n\t"
      "movswl 0xc(%%esi), %%edx\n\t"
      "incl %%ebx\n\t"
      "movswl %%bx, %%eax\n\t"
      "decl %%edx\n\t"
      "cmpl %%edx, %%eax\n\t"
      "jl .Lflag_render_proper_12\n\t"
      "movl 0x8(%%ebp), %%edi\n\t"
      ".Lflag_render_proper_29:\n\t"
      "movl -0x14(%%ebp), %%ecx\n\t"
      "pushl %%ecx\n\t"
      "call *%[c17c990]\n\t"
      "movl -0xc(%%ebp), %%edx\n\t"
      "pushl %%edx\n\t"
      "call *%[rend]\n\t"
      "movl -0x18(%%ebp), %%eax\n\t"
      "pushl %%eax\n\t"
      "pushl $0x73686472\n\t"
      "call *%[tag]\n\t"
      "addl $0x10, %%esp\n\t"
      "cmpw $0, 0xc(%%esi)\n\t"
      "movl %%eax, -0x30(%%ebp)\n\t"
      "jg .Lflag_render_proper_30\n\t"
      "pushl $1\n\t"
      "pushl $0x61\n\t"
      "pushl $0x29aa38\n\t"
      "pushl $0x29aa08\n\t"
      "call *%[assert]\n\t"
      "pushl $-1\n\t"
      "call *%[exitfn]\n\t"
      "addl $0x14, %%esp\n\t"
      ".Lflag_render_proper_30:\n\t"
      "cmpw $0, 0xe(%%esi)\n\t"
      "jg .Lflag_render_proper_31\n\t"
      "pushl $1\n\t"
      "pushl $0x62\n\t"
      "pushl $0x29aa38\n\t"
      "pushl $0x29a9e8\n\t"
      "call *%[assert]\n\t"
      "pushl $-1\n\t"
      "call *%[exitfn]\n\t"
      "addl $0x14, %%esp\n\t"
      ".Lflag_render_proper_31:\n\t"
      "xorl %%ecx, %%ecx\n\t"
      "movw 0xc(%%esi), %%cx\n\t"
      "decw %%cx\n\t"
      "pushl $0\n\t"
      "pushl %%ecx\n\t"
      "pushl %%esi\n\t"
      "pushl %%edi\n\t"
      "call *%[c131840]\n\t"
      "xorl %%edx, %%edx\n\t"
      "movw 0xe(%%esi), %%dx\n\t"
      "decw %%dx\n\t"
      "movl %%eax, %%ebx\n\t"
      "pushl %%edx\n\t"
      "pushl $0\n\t"
      "pushl %%esi\n\t"
      "pushl %%edi\n\t"
      "call *%[c131840]\n\t"
      "movl %%eax, 0x8(%%ebp)\n\t"
      "xorl %%eax, %%eax\n\t"
      "movw 0xe(%%esi), %%ax\n\t"
      "xorl %%ecx, %%ecx\n\t"
      "movw 0xc(%%esi), %%cx\n\t"
      "decw %%ax\n\t"
      "decw %%cx\n\t"
      "pushl %%eax\n\t"
      "pushl %%ecx\n\t"
      "pushl %%esi\n\t"
      "pushl %%edi\n\t"
      "call *%[c131840]\n\t"
      "flds (%%eax)\n\t"
      "movl 0x8(%%ebp), %%ecx\n\t"
      "fadds (%%ecx)\n\t"
      "pushl $0xcc\n\t"
      "leal -0x160(%%ebp), %%edx\n\t"
      "pushl $0\n\t"
      "fadds (%%ebx)\n\t"
      "pushl %%edx\n\t"
      "fadds 0x1c(%%edi)\n\t"
      "fmuls 0x25337c\n\t"
      "fstps -0x28(%%ebp)\n\t"
      "flds 0x4(%%eax)\n\t"
      "fadds 0x4(%%ecx)\n\t"
      "fadds 0x4(%%ebx)\n\t"
      "fadds 0x20(%%edi)\n\t"
      "fmuls 0x25337c\n\t"
      "fstps -0x24(%%ebp)\n\t"
      "flds 0x8(%%eax)\n\t"
      "fadds 0x8(%%ecx)\n\t"
      "fadds 0x8(%%ebx)\n\t"
      "fadds 0x24(%%edi)\n\t"
      "fmuls 0x25337c\n\t"
      "fstps -0x20(%%ebp)\n\t"
      "call *%[memset]\n\t"
      "movl 0x31fc60, %%eax\n\t"
      "movl 0x10(%%ebp), %%esi\n\t"
      "movl %%eax, -0x158(%%ebp)\n\t"
      "movl 0x14(%%ebp), %%eax\n\t"
      "movl 0x4(%%eax), %%edx\n\t"
      "movl $1, %%ebx\n\t"
      "movl %%ebx, -0x15c(%%ebp)\n\t"
      "movw %%bx, -0x154(%%ebp)\n\t"
      "movl $0x1d, %%ecx\n\t"
      "leal -0x150(%%ebp), %%edi\n\t"
      "rep movsl\n\t"
      "movl (%%eax), %%ecx\n\t"
      "movl -0x28(%%ebp), %%eax\n\t"
      "movl %%ecx, -0xdc(%%ebp)\n\t"
      "movl -0x24(%%ebp), %%ecx\n\t"
      "movl %%edx, -0xd8(%%ebp)\n\t"
      "movl -0x20(%%ebp), %%edx\n\t"
      "pushl $0\n\t"
      "movl %%eax, -0xac(%%ebp)\n\t"
      "movl %%ecx, -0xa8(%%ebp)\n\t"
      "movl %%edx, -0xa4(%%ebp)\n\t"
      "movl $0x3f800000, -0x98(%%ebp)\n\t"
      "movl $0x3f800000, -0x9c(%%ebp)\n\t"
      "call *%[c17c960]\n\t"
      "addl $0x40, %%esp\n\t"
      "pushl $0\n\t"
      "call *%[c17d1a0]\n\t"
      "leal -0x160(%%ebp), %%eax\n\t"
      "pushl $0\n\t"
      "pushl %%eax\n\t"
      "call *%[c17cbb0]\n\t"
      "movl -0x30(%%ebp), %%esi\n\t"
      "xorl %%ecx, %%ecx\n\t"
      "movw 0x24(%%esi), %%cx\n\t"
      "pushl %%ecx\n\t"
      "call *%[c1909d0]\n\t"
      "movswl 0xc(%%ebp), %%ecx\n\t"
      "addl $0x10, %%esp\n\t"
      "testb %%al, %%al\n\t"
      "movl -0xc(%%ebp), %%eax\n\t"
      "je .Lflag_render_proper_32\n\t"
      "pushl $0\n\t"
      "leal -0x28(%%ebp), %%edx\n\t"
      "pushl %%edx\n\t"
      "movl -0x14(%%ebp), %%edx\n\t"
      "pushl %%eax\n\t"
      "pushl $0\n\t"
      "pushl %%ecx\n\t"
      "pushl %%edx\n\t"
      "pushl $0\n\t"
      "pushl $0\n\t"
      "pushl %%esi\n\t"
      "call *%[c17cbd0]\n\t"
      "addl $0x24, %%esp\n\t"
      "jmp .Lflag_render_proper_33\n\t"
      ".Lflag_render_proper_32:\n\t"
      "movl -0x14(%%ebp), %%edx\n\t"
      "pushl %%eax\n\t"
      "pushl $0\n\t"
      "pushl %%ecx\n\t"
      "pushl %%edx\n\t"
      "pushl $0\n\t"
      "pushl $0\n\t"
      "pushl %%esi\n\t"
      "call *%[c17cbc0]\n\t"
      "addl $0x1c, %%esp\n\t"
      ".Lflag_render_proper_33:\n\t"
      "call *%[c17cbe0]\n\t"
      "call *%[c17cbf0]\n\t"
      "pushl %%ebx\n\t"
      "call *%[c17c960]\n\t"
      "movl -0x14(%%ebp), %%ebx\n\t"
      "addl $4, %%esp\n\t"
      ".Lflag_render_proper_34:\n\t"
      "pushl %%ebx\n\t"
      "call *%[c17c9a0]\n\t"
      "movl -0xc(%%ebp), %%eax\n\t"
      "pushl %%eax\n\t"
      "call *%[rocc]\n\t"
      "addl $8, %%esp\n\t"
      "popl %%edi\n\t"
      "popl %%esi\n\t"
      "movw $0, 0x325652\n\t"
      "popl %%ebx\n\t"
      "movl %%ebp, %%esp\n\t"
      "popl %%ebp\n\t"
      "ret\n\t"
      ".section .rdata,\"dr\"\n\t"
      ".Lflag_render_proper_jt:\n\t"
      ".long .Lflag_render_proper_14\n\t"
      ".long .Lflag_render_proper_27\n\t"
      ".long .Lflag_render_proper_17\n\t"
      ".long .Lflag_render_proper_19\n\t"
      ".long .Lflag_render_proper_21\n\t"
      ".long .Lflag_render_proper_23\n\t"
      ".text\n\t"
      :
      : [get] "m"(b132460_get), [c17c970] "m"(b132460_c17c970), [rzbuf] "m"(b132460_rzbuf), [tag] "m"(b132460_tag), [rspr] "m"(b132460_rspr), [c17c980] "m"(b132460_c17c980), [memset] "m"(b132460_memset), [c131840] "m"(b132460_c131840), [c180d10] "m"(b132460_c180d10), [c1318f0] "m"(b132460_c1318f0), [assert] "m"(b132460_assert), [exitfn] "m"(b132460_exitfn), [c17c990] "m"(b132460_c17c990), [rend] "m"(b132460_rend), [c17c960] "m"(b132460_c17c960), [c17d1a0] "m"(b132460_c17d1a0), [c17cbb0] "m"(b132460_c17cbb0), [c1909d0] "m"(b132460_c1909d0), [c17cbd0] "m"(b132460_c17cbd0), [c17cbc0] "m"(b132460_c17cbc0), [c17cbe0] "m"(b132460_c17cbe0), [c17cbf0] "m"(b132460_c17cbf0), [c17c9a0] "m"(b132460_c17c9a0), [rocc] "m"(b132460_rocc)
      : "memory");
}
#else
#error "flag_render_proper: clang naked draft required"
#endif

